
import { CollectionSchema, FieldType } from './types';

const YES_NO_UNKNOWN = [
  { label: 'Tak', value: 'tak' },
  { label: 'Nie', value: 'nie' },
  { label: 'Nieznane', value: 'nieznane' }
];

const YES_NO = [
  { label: 'Tak', value: 'tak' },
  { label: 'Nie', value: 'nie' }
];

const GRADE_NONE_SEVERE = [
  { label: 'Brak', value: 'none' },
  { label: 'Mała', value: 'mild' },
  { label: 'Umiarkowana', value: 'moderate' },
  { label: 'Duża', value: 'severe' }
];

export const DATA_SCHEMA: CollectionSchema = [
  {
    id: 'sec_a_admin',
    title: 'Sekcja A: Dane Administracyjne',
    description: 'Dokumentacja identyfikacyjna v1.1',
    fields: [
      { id: 'study_number', label: 'Numer badania', type: FieldType.TEXT, required: true },
      { id: 'center_code', label: 'Kod ośrodka', type: FieldType.TEXT, required: true },
      { id: 'patient_first_name', label: 'Imię pacjenta', type: FieldType.TEXT, required: true },
      { id: 'patient_last_name', label: 'Nazwisko pacjenta', type: FieldType.TEXT, required: true },
      { id: 'inclusion_date', label: 'Data włączenia', type: FieldType.DATE, required: true },
      { id: 'collector_initials', label: 'Inicjały osoby zbierającej dane', type: FieldType.TEXT, required: true }
    ]
  },
  {
    id: 'sec_b_demo',
    title: 'Sekcja B: Dane Demograficzne',
    description: 'Charakterystyka pacjenta v1.1',
    fields: [
      { id: 'dob', label: 'Data urodzenia', type: FieldType.DATE },
      { id: 'age', label: 'Wiek w dniu zabiegu', type: FieldType.NUMBER, unit: 'lat' },
      { id: 'sex', label: 'Płeć', type: FieldType.RADIO, options: [{label: 'Mężczyzna', value: 'm'}, {label: 'Kobieta', value: 'k'}] },
      { id: 'height', label: 'Wzrost', type: FieldType.NUMBER, unit: 'cm' },
      { id: 'weight', label: 'Masa ciała', type: FieldType.NUMBER, unit: 'kg' },
      { id: 'bmi', label: 'BMI (obliczone)', type: FieldType.NUMBER, unit: 'kg/m2' },
      { id: 'smoking_status', label: 'Status palenia', type: FieldType.SELECT, options: [{label: 'Nigdy', value: 'nigdy'}, {label: 'Były palacz (>1 rok)', value: 'byly'}, {label: 'Aktualny palacz', value: 'aktualny'}] }
    ]
  },
  {
    id: 'sec_c_comorb',
    title: 'Sekcja C: Choroby Współistniejące',
    description: 'Obciążenia i wywiad (v1.1 - ROZSZERZONA)',
    fields: [
      { id: 'hdr_c_cv', label: 'UKŁAD SERCOWO-NACZYNIOWY', type: FieldType.SECTION_HEADER },
      { id: 'htn', label: 'Nadciśnienie tętnicze', type: FieldType.RADIO, options: YES_NO },
      { id: 'cad', label: 'Choroba wieńcowa', type: FieldType.RADIO, options: YES_NO },
      { id: 'mi_history', label: 'Przebyty zawał serca', type: FieldType.RADIO, options: YES_NO },
      { id: 'heart_failure_nyha', label: 'Niewydolność serca (NYHA)', type: FieldType.SELECT, options: [{label: 'NYHA I', value: '1'}, {label: 'NYHA II', value: '2'}, {label: 'NYHA III', value: '3'}, {label: 'NYHA IV', value: '4'}, {label: 'Brak', value: '0'}] },
      { id: 'afib', label: 'Migotanie przedsionków', type: FieldType.RADIO, options: YES_NO },
      { id: 'prev_cardio_sx', label: 'Przebyta operacja kardiochirurgiczna', type: FieldType.RADIO, options: YES_NO },
      { id: 'pfo_history', label: 'Przetrwały otwór owalny (PFO)', type: FieldType.RADIO, options: YES_NO },
      { id: 'other_shunt', label: 'Inny przeciek wewnątrzsercowy', type: FieldType.RADIO, options: YES_NO },
      { id: 'pad', label: 'Miażdżyca tt. obwodowych', type: FieldType.RADIO, options: YES_NO },
      { id: 'hdr_c_stentgraft', label: 'Stan po stentgrafcie', type: FieldType.SECTION_HEADER },
      { id: 'prior_stentgraft_yn', label: 'Przebyty zabieg stentgraftowania', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'prior_stentgraft_type', label: 'Typ stentgraftu', type: FieldType.SELECT, options: [{label: 'BEVAR', value: 'bevar'}, {label: 'TEVAR', value: 'tevar'}, {label: 'EVAR', value: 'evar'}, {label: 'IBD', value: 'ibd'}], conditional: { dependsOn: 'prior_stentgraft_yn', disableWhen: ['nie', 'nieznane'], greyOut: true } },
      { id: 'prior_stentgraft_date', label: 'Data zabiegu', type: FieldType.DATE, conditional: { dependsOn: 'prior_stentgraft_yn', disableWhen: ['nie', 'nieznane'], greyOut: true } },
      { id: 'hdr_c_cardiac_sx', label: 'Przebyta operacja kardiochirurgiczna', type: FieldType.SECTION_HEADER },
      { id: 'prior_cardiac_sx_type', label: 'Typ operacji', type: FieldType.SELECT, options: [{label: 'Op. Bentalla (zast. sztuczna)', value: 'bentalla_synthetic'}, {label: 'Op. Bentalla (zast. biologiczna)', value: 'bentalla_biologic'}, {label: 'Proteza ascendente', value: 'prosthesis_asc'}, {label: 'CABG', value: 'cabg'}, {label: 'Inna', value: 'other'}] },
      { id: 'synthetic_valve_diam', label: 'Jeśli zastawka sztuczna - średnica', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'cardiac_sx_technique', label: 'Technika przy implantacji', type: FieldType.SELECT, options: [{label: 'Przejście przez zastawkę', value: 'through_valve'}, {label: 'Loop technique', value: 'loop'}, {label: 'N/D', value: 'nd'}] },
      { id: 'hdr_c_neuro_ext', label: 'UKŁAD MÓZGOWO-NACZYNIOWY - ROZSZERZONA OCENA', type: FieldType.SECTION_HEADER },
      { id: 'stroke_isch', label: 'Przebyty udar niedokrwienny', type: FieldType.RADIO, options: YES_NO },
      { id: 'stroke_hem', label: 'Przebyty udar krwotoczny', type: FieldType.RADIO, options: YES_NO },
      { id: 'stroke_tia', label: 'Przebyty TIA', type: FieldType.RADIO, options: YES_NO },
      { id: 'carotid_stenosis_gt50', label: 'Zwężenie t. szyjnej (>50%)', type: FieldType.RADIO, options: YES_NO },
      { id: 'cea_stent_history', label: 'Endarterektomia / Stent t. szyjnej', type: FieldType.RADIO, options: YES_NO },
      { id: 'cognitive_impairment', label: 'Zaburzenia poznawcze', type: FieldType.RADIO, options: YES_NO },
      { id: 'hdr_c_incidents', label: 'SZCZEGÓŁY PRZEBYTYCH INCYDENTÓW', type: FieldType.SECTION_HEADER },
      { id: 'stroke_count', label: 'Liczba przebytych udarów', type: FieldType.NUMBER },
      { id: 'last_stroke_date', label: 'Data ostatniego udaru/TIA', type: FieldType.DATE, conditional: { dependsOn: 'stroke_count', disableWhen: ['0', ''], greyOut: true } },
      { id: 'time_from_stroke_months', label: 'Czas od ostatniego udaru do zabiegu', type: FieldType.NUMBER, unit: 'miesięcy' },
      { id: 'stroke_area', label: 'Obszar przebytego udaru', type: FieldType.SELECT, options: [{label: 'MCA', value: 'mca'}, {label: 'ACA', value: 'aca'}, {label: 'PCA', value: 'pca'}, {label: 'Kręgowo-podstawny', value: 'vb'}, {label: 'Mnogie', value: 'multi'}, {label: 'Nieznany', value: 'unk'}] },
      { id: 'permanent_neuro_deficit', label: 'Trwały deficyt neurologiczny', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'pre_proc_mrs', label: 'mRS przed obecnym zabiegiem', type: FieldType.NUMBER, unit: '/6' },
      { id: 'hdr_c_other', label: 'INNE CHOROBY WSPÓŁISTNIEJĄCE', type: FieldType.SECTION_HEADER },
      { id: 'dm', label: 'Cukrzyca', type: FieldType.RADIO, options: YES_NO },
      { id: 'copd', label: 'POChP', type: FieldType.RADIO, options: YES_NO },
      { id: 'chronic_kidney', label: 'Przewlekła choroba nerek', type: FieldType.RADIO, options: YES_NO },
      { id: 'dialysis', label: 'Dializoterapia', type: FieldType.RADIO, options: YES_NO },
      { id: 'connective_tissue_disease', label: 'Choroba tkanki łącznej', type: FieldType.RADIO, options: YES_NO },
      { id: 'active_cancer', label: 'Nowotwór złośliwy (aktywny)', type: FieldType.RADIO, options: YES_NO },
      { id: 'hdr_c_labs', label: 'WYNIKI WYJŚCIOWE', type: FieldType.SECTION_HEADER },
      { id: 'baseline_egfr', label: 'Wyjściowy eGFR', type: FieldType.NUMBER, unit: 'mL/min/1.73m2' },
      { id: 'baseline_creat', label: 'Wyjściowa kreatynina', type: FieldType.NUMBER, unit: 'umol/L' },
      { id: 'baseline_hb', label: 'Wyjściowa hemoglobina', type: FieldType.NUMBER, unit: 'g/dL' },
      { id: 'post_procedure_hb', label: 'Hemoglobina po zabiegu', type: FieldType.NUMBER, unit: 'g/dL' },
      { id: 'hdr_c_ct_details', label: 'TYP CHOROBY TKANKI ŁĄCZNEJ', type: FieldType.SECTION_HEADER },
      { id: 'ct_type', label: 'Typ choroby', type: FieldType.SELECT, options: [{label: 'Marfan', value: 'marfan'}, {label: 'Loeys-Dietz', value: 'loeys'}, {label: 'Ehlers-Danlos', value: 'ehlers'}, {label: 'Inna', value: 'inna'}] },
      { id: 'ct_dx_age', label: 'Wiek w momencie rozpoznania', type: FieldType.NUMBER, unit: 'lat' }
    ]
  },
  {
    id: 'sec_d_patho',
    title: 'Sekcja D: Wskazanie i Patologia Aorty',
    description: 'Anatomia i morfologia (v1.1 - ROZSZERZONA)',
    fields: [
      { id: 'hdr_d_indication', label: 'GŁÓWNE WSKAZANIE', type: FieldType.SECTION_HEADER },
      { id: 'primary_indication', label: 'Wskazanie', type: FieldType.SELECT, options: [{label: 'Tętniak', value: 'tetniak'}, {label: 'Rozwarstwienie', value: 'rozwarstwienie'}, {label: 'Krwiak śródścienny', value: 'imh'}, {label: 'Wrzód drążący', value: 'ulcer'}, {label: 'Urazowe', value: 'trauma'}, {label: 'Inne', value: 'inne'}] },
      { id: 'post_bentalla', label: 'Po operacji Bentalla', type: FieldType.RADIO, options: [{label: 'Tak (zast. sztuczna)', value: 'synthetic'}, {label: 'Tak (zast. biologiczna)', value: 'biologic'}, {label: 'Proteza ascendente', value: 'prosthesis'}, {label: 'Nie', value: 'no'}] },
      { id: 'hdr_d_aneurysm', label: 'W PRZYPADKU TĘTNIAKA', type: FieldType.SECTION_HEADER },
      { id: 'aneurysm_max_diam', label: 'Maksymalna średnica tętniaka', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'aneurysm_loc', label: 'Lokalizacja tętniaka', type: FieldType.SELECT, options: [{label: 'Aorta wstępująca', value: 'asc'}, {label: 'Łuk aorty', value: 'arch'}, {label: 'Zstępująca proksym.', value: 'desc_p'}, {label: 'Wiele segmentów', value: 'multi'}] },
      { id: 'aneurysm_size_cat', label: '[NOWE] Kategoria wielkości tętniaka', type: FieldType.SELECT, options: [{label: '<50 mm', value: 'lt50'}, {label: '50-59 mm', value: '50_59'}, {label: '60-69 mm', value: '60_69'}, {label: '70-79 mm', value: '70_79'}, {label: '>=80 mm', value: 'ge80'}] },
      { id: 'aneurysm_gt_70', label: '[NOWE] Tętniak >= 70 mm', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'aneurysm_symptomatic', label: 'Objawowy', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'aneurysm_rupture_cont', label: 'Pęknięcie ograniczone', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_d_dissection', label: 'W PRZYPADKU ROZWARSTWIENIA', type: FieldType.SECTION_HEADER },
      { id: 'stanford_class', label: 'Klasyfikacja Stanford', type: FieldType.RADIO, options: [{label: 'Typ A', value: 'a'}, {label: 'Typ B', value: 'b'}] },
      { id: 'debakey_class', label: 'Klasyfikacja DeBakey', type: FieldType.SELECT, options: [{label: 'I', value: '1'}, {label: 'II', value: '2'}, {label: 'IIIa', value: '3a'}, {label: 'IIIb', value: '3b'}] },
      { id: 'dissection_phase', label: 'Faza', type: FieldType.RADIO, options: [{label: 'Ostre (<14 dni)', value: 'acute'}, {label: 'Podostre (14-90 dni)', value: 'subacute'}, {label: 'Przewlekłe (>90 dni)', value: 'chronic'}] },
      { id: 'malperfusion_syndrome', label: 'Zespół niedokrwienia narządowego (malperfuzja)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'dissection_entry_zone', label: 'Proksymalny (Entry) - zona SVS/STS', type: FieldType.SELECT, options: [{label: 'Zone 0', value: '0'}, {label: 'Zone 1', value: '1'}, {label: 'Zone 2', value: '2'}, {label: 'Zone 3', value: '3'}, {label: 'Zone 4', value: '4'}, {label: 'Zone 5', value: '5'}, {label: 'Zone 6', value: '6'}, {label: 'Zone 7', value: '7'}, {label: 'Zone 8', value: '8'}, {label: 'Zone 9', value: '9'}, {label: 'Zone 10', value: '10'}, {label: 'Zone 11', value: '11'}, {label: 'Zone 12', value: '12'}] },
      { id: 'dissection_reentry_zone', label: 'Dystalny (Re-entry) - zona SVS/STS', type: FieldType.SELECT, options: [{label: 'Zone 0', value: '0'}, {label: 'Zone 1', value: '1'}, {label: 'Zone 2', value: '2'}, {label: 'Zone 3', value: '3'}, {label: 'Zone 4', value: '4'}, {label: 'Zone 5', value: '5'}, {label: 'Zone 6', value: '6'}, {label: 'Zone 7', value: '7'}, {label: 'Zone 8', value: '8'}, {label: 'Zone 9', value: '9'}, {label: 'Zone 10', value: '10'}, {label: 'Zone 11', value: '11'}, {label: 'Zone 12', value: '12'}] },
      { id: 'hdr_d_secondary_gates', label: 'Włazowe wrota rozwarstwienia w tt. dęogłowowych', type: FieldType.SECTION_HEADER },
      { id: 'rcca_status', label: 'RCCA', type: FieldType.SELECT, options: [{label: 'Ucśnięty k. prawdziwy', value: 'compressed'}, {label: 'Stent w trakcie', value: 'stent'}, {label: 'Bez stentu', value: 'no_stent'}, {label: 'Brak zajęcia', value: 'none'}] },
      { id: 'lcca_status', label: 'LCCA', type: FieldType.SELECT, options: [{label: 'Ucśnięty k. prawdziwy', value: 'compressed'}, {label: 'Stent w trakcie', value: 'stent'}, {label: 'Bez stentu', value: 'no_stent'}, {label: 'Brak zajęcia', value: 'none'}] },
      { id: 'lsa_status', label: 'LSA', type: FieldType.SELECT, options: [{label: 'Ucśnięty k. prawdziwy', value: 'compressed'}, {label: 'Stent w trakcie', value: 'stent'}, {label: 'Bez stentu', value: 'no_stent'}, {label: 'Brak zajęcia', value: 'none'}] },
      { id: 'bct_status', label: 'BCT', type: FieldType.SELECT, options: [{label: 'Ucśnięty k. prawdziwy', value: 'compressed'}, {label: 'Stent w trakcie', value: 'stent'}, {label: 'Bez stentu', value: 'no_stent'}, {label: 'Brak zajęcia', value: 'none'}] },
      { id: 'hdr_d_pau', label: 'W przypadku PAU', type: FieldType.SECTION_HEADER },
      { id: 'pau_depth', label: 'Głębokość PAU', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'pau_width', label: 'Szerokość szyi PAU', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'pau_zone', label: 'Lokalizacja PAU (strefa)', type: FieldType.NUMBER },
      { id: 'hdr_d_fl', label: '[NOWE] WYMIARY KANAŁU FAŁSZYWEGO', type: FieldType.SECTION_HEADER },
      { id: 'fl_max_width', label: 'Maks. szerokość kanału fałszywego', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'fl_arch_width', label: 'Szerokość na poziomie łuku', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'fl_thrombus_present', label: 'Skrzeplina w kanale fałszywym', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'fl_thrombosis_grade', label: 'Stopień zakrzepicy k. fałszywego', type: FieldType.SELECT, options: [{label: 'Brak', value: 'none'}, {label: 'Częściowa (<50%)', value: 'part_lt50'}, {label: 'Częściowa (>=50%)', value: 'part_ge50'}, {label: 'Pełna', value: 'full'}] },
      { id: 'hdr_d_key_analysis', label: '[NOWE] WYMIARY AORTY - KLUCZOWE DLA ANALIZY', type: FieldType.SECTION_HEADER },
      { id: 'asc_aorta_diam', label: 'Średnica aorty wstępującej', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'stj_diam', label: 'Złącze zatokowo-tubularne (STJ)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'asc_aorta_cat', label: 'Kategoria śr. aorty wstępującej', type: FieldType.SELECT, options: [{label: '<=36 mm', value: 'le36'}, {label: '>36 do <=40 mm', value: '36_40'}, {label: '>40 mm', value: 'gt40'}] },
      { id: 'asc_aorta_ge_40', label: 'Średnica aorty wstępującej >= 40 mm', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'arch_diam', label: 'Średnica łuku aorty', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'desc_aorta_lsa_diam', label: 'Aorta zstępująca (przy LSA)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'zone0_length', label: 'Długość strefy 0', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'zone2_length', label: 'Długość strefy 2', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'diam_diff_asc_landing', label: 'Różnica średnic (aorta wstęp. - strefa ladowania)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'hdr_d_morphology', label: 'MORFOLOGIA AORTY', type: FieldType.SECTION_HEADER },
      { id: 'arch_type_ishimaru', label: 'Typ łuku (Ishimaru)', type: FieldType.RADIO, options: [{label: 'Typ I', value: '1'}, {label: 'Typ II', value: '2'}, {label: 'Typ III', value: '3'}] },
      { id: 'shaggy_aorta', label: 'Aorta shaggy (ruchome blaszki miażdż.)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'shaggy_thickness_max', label: '[NOWE] Jeśli shaggy - maks. grubość blaszki', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'shaggy_location', label: '[NOWE] Lokalizacja shaggy', type: FieldType.SELECT, options: [{label: 'Aorta wstępująca', value: 'asc'}, {label: 'Łuk', value: 'arch'}, {label: 'Aorta zstępująca', value: 'desc'}, {label: 'Mnogie', value: 'multi'}] },
      { id: 'thrombus_in_arch', label: 'Skrzeplina w łuku aorty', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'thrombus_in_asc', label: 'Skrzeplina w aorcie wstępującej', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'porcelain_aorta', label: 'Aorta porcelanowa (zwapnienia obwodowe)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'supraaortic_vessels_inv', label: 'Zajęcie tt. nadaortalnych', type: FieldType.SELECT, options: [{label: 'Brak', value: 'none'}, {label: 'BCT', value: 'bct'}, {label: 'LCCA', value: 'lcca'}, {label: 'LSA', value: 'lsa'}, {label: 'Wiele', value: 'multi'}] }
    ]
  },
  {
    id: 'sec_e_neuro_pre',
    title: 'Sekcja E: Przedoperacyjna Ocena Naczyń Mózgowych',
    description: 'Angio-TK i Koło Willisa (v1.1 - ROZSZERZONA)',
    fields: [
      { id: 'hdr_e_tk', label: 'ANGIO-TK GŁOWY (KOŁO WILLISA)', type: FieldType.SECTION_HEADER },
      { id: 'angio_tk_done', label: 'Wykonano angio-TK głowy', type: FieldType.RADIO, options: YES_NO },
      { id: 'angio_tk_date', label: 'Data angio-TK głowy', type: FieldType.DATE },
      { id: 'hdr_e_ant', label: 'KRĄŻENIE PRZEDNIE', type: FieldType.SECTION_HEADER },
      { id: 'acom_patent', label: 'Tętnica łącząca przednia (ACom) drożna', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'acom_diam', label: 'Średnica ACom (jeśli zmierzono)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'segment_a1_aca', label: 'Segment A1 (ACA)', type: FieldType.SELECT, options: [{label: 'Obustronnie drożny', value: 'both'}, {label: 'Dominacja prawa', value: 'r_dom'}, {label: 'Dominacja lewa', value: 'l_dom'}, {label: 'Hipoplazja/brak', value: 'hypo'}] },
      { id: 'hdr_e_post', label: 'KRĄŻENIE TYLNE', type: FieldType.SECTION_HEADER },
      { id: 'r_pcom_patent', label: 'Prawa t. łącząca tylna (PCom) drożna', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'r_pcom_diam', label: 'Średnica prawej PCom', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'l_pcom_patent', label: 'Lewa t. łącząca tylna (PCom) drożna', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'l_pcom_diam', label: 'Średnica lewej PCom', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'willis_classification', label: 'Klasyfikacja Koła Willisa', type: FieldType.CHECKBOX, options: [{label: 'Pełne', value: 'full'}, {label: 'Niepełne przednie', value: 'inc_ant'}, {label: 'Niepełne tylne', value: 'inc_post'}, {label: 'Niepełne oba', value: 'inc_both'}] },
      { id: 'hdr_e_vb', label: 'UKŁAD KRĘGOWO-PODSTAWNY', type: FieldType.SECTION_HEADER },
      { id: 'r_va_status', label: 'Prawa t. kręgowa', type: FieldType.SELECT, options: [{label: 'Drożna (V1-V4)', value: 'patent'}, {label: 'Hipoplastyczna (<2 mm)', value: 'hypo'}, {label: 'Krytycznie zwężone ostium (V1)', value: 'crit_stenosis_v1'}, {label: 'Kończy się w PICA', value: 'pica'}, {label: 'Niedrożna', value: 'occl'}, {label: 'Nie oceniano', value: 'na'}] },
      { id: 'r_va_pathology', label: 'Prawa t. kręgowa - patologia', type: FieldType.SELECT, options: [{label: 'Zwezenie', value: 'stenosis'}, {label: 'Skrzepliny', value: 'thrombosis'}, {label: 'Dysekcja', value: 'dissection'}, {label: 'Brak patologii', value: 'none'}] },
      { id: 'l_va_status', label: 'Lewa t. kręgowa', type: FieldType.SELECT, options: [{label: 'Drożna (V1-V4)', value: 'patent'}, {label: 'Hipoplastyczna (<2 mm)', value: 'hypo'}, {label: 'Krytycznie zwężone ostium (V1)', value: 'crit_stenosis_v1'}, {label: 'Kończy się w PICA', value: 'pica'}, {label: 'Niedrożna', value: 'occl'}, {label: 'Nie oceniano', value: 'na'}] },
      { id: 'l_va_pathology', label: 'Lewa t. kręgowa - patologia', type: FieldType.SELECT, options: [{label: 'Zwezenie', value: 'stenosis'}, {label: 'Skrzepliny', value: 'thrombosis'}, {label: 'Dysekcja', value: 'dissection'}, {label: 'Brak patologii', value: 'none'}] },
      { id: 'va_dominance', label: 'Dominacja t. kręgowej', type: FieldType.SELECT, options: [{label: 'Kodominacja', value: 'codom'}, {label: 'Dominacja prawa', value: 'r_dom'}, {label: 'Dominacja lewa', value: 'l_dom'}] },
      { id: 'r_va_diam', label: 'Średnica prawej VA', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'l_va_diam', label: 'Średnica lewej VA', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'basilar_patent', label: 'Tętnica podstawna drożna', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_e_carotid', label: 'OCENA TĘTNIC SZYJNYCH', type: FieldType.SECTION_HEADER },
      { id: 'r_ica_status', label: 'Prawa ICA', type: FieldType.SELECT, options: [{label: 'Drożna', value: 'patent'}, {label: 'Zwężenie <50%', value: 'sten_lt50'}, {label: 'Zwężenie 50-69%', value: 'sten_50_69'}, {label: 'Zwężenie 70-99%', value: 'sten_70_99'}, {label: 'Niedrożna', value: 'occl'}] },
      { id: 'l_ica_status', label: 'Lewa ICA', type: FieldType.SELECT, options: [{label: 'Drożna', value: 'patent'}, {label: 'Zwężenie <50%', value: 'sten_lt50'}, {label: 'Zwężenie 50-69%', value: 'sten_50_69'}, {label: 'Zwężenie 70-99%', value: 'sten_70_99'}, {label: 'Niedrożna', value: 'occl'}] },
      { id: 'hdr_e_risk', label: 'KLASYFIKACJA RYZYKA - PODSUMOWANIE', type: FieldType.SECTION_HEADER },
      { id: 'posterior_risk', label: 'Ryzyko krążenia tylnego', type: FieldType.SELECT, options: [{label: 'Niskie (pełne PCom, kodom. VA)', value: 'low'}, {label: 'Umiarkowane (jednostr. PCom)', value: 'med'}, {label: 'Wysokie (brak PCom, pojedyncza VA)', value: 'high'}] },
      { id: 'willis_risk_total', label: 'Ryzyko Koła Willisa - ŁĄCZNIE', type: FieldType.SELECT, options: [{label: 'Niskie (all VA\'s patent)', value: 'low_all_patent'}, {label: 'Umiarkowane (brak obu PCom przy kodominacji VA)', value: 'moderate_no_pcom'}, {label: 'Umiarkowane (jedna VA niewydolna)', value: 'moderate_one_va'}, {label: 'Wysokie (obie VA niewydolne)', value: 'high_both_va'}, {label: 'Nieznane', value: 'unknown'}] }
    ]
  },
  {
    id: 'sec_f_cardiac',
    title: 'Sekcja F: Przedoperacyjna Ocena Kardiologiczna',
    description: 'ECHO i Coronary Angio (v1.1 - PEŁNA)',
    fields: [
      { id: 'hdr_f_consult', label: 'KONSULTACJA', type: FieldType.SECTION_HEADER },
      { id: 'cardio_consult_done', label: 'Wykonano konsultację kardiologiczną', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'cardio_consult_date', label: 'Data konsultacji', type: FieldType.DATE },
      { id: 'hdr_f_echo', label: 'ECHOKARDIOGRAFIA', type: FieldType.SECTION_HEADER },
      { id: 'echo_type', label: 'Wykonano echokardiografię', type: FieldType.SELECT, options: [{label: 'TTE', value: 'tte'}, {label: 'TEE', value: 'tee'}, {label: 'Oba', value: 'both'}, {label: 'Nie wykonano', value: 'none'}] },
      { id: 'lvef_perc', label: 'LVEF (%)', type: FieldType.NUMBER, unit: '%' },
      { id: 'lv_function', label: 'Funkcja LK', type: FieldType.SELECT, options: [{label: 'Prawidłowa (>=55%)', value: 'norm'}, {label: 'Łagodna (45-54%)', value: 'mild'}, {label: 'Umiarkowana (30-44%)', value: 'mod'}, {label: 'Ciężka (<30%)', value: 'severe'}] },
      { id: 'aortic_insuf_grade', label: 'Niedomykałność aortalna (umiarkowana lub większa)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'aortic_sten_grade', label: 'Stenoza aortalna', type: FieldType.SELECT, options: GRADE_NONE_SEVERE },
      { id: 'pfo_detected', label: 'Wykryto przetrwały otwór owalny (PFO)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'asd_detected', label: 'Wykryto ubytek przegrody międzyprzedsionkowej', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'laa_thrombus', label: 'Skrzeplina w uszku lewego przedsionka', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_f_coronary', label: 'OCENA TĘTNIC WIEŃCOWYCH', type: FieldType.SECTION_HEADER },
      { id: 'coronary_eval_method', label: 'Metoda oceny tt. wieńcowych', type: FieldType.SELECT, options: [{label: 'Angio-TK tt. wieńcowych', value: 'ct'}, {label: 'Koronarografia inwazyjna', value: 'angio'}, {label: 'Testy obciążeniowe', value: 'stress'}, {label: 'Nie wykonano', value: 'none'}] },
      { id: 'cad_status', label: 'Choroba wieńcowa', type: FieldType.SELECT, options: [{label: 'Brak', value: 'none'}, {label: 'Nieobturacyjna', value: 'non_obt'}, {label: '1-naczyniowa', value: '1v'}, {label: '2-naczyniowa', value: '2v'}, {label: '3-naczyniowa', value: '3v'}, {label: 'Pień lewej', value: 'main_l'}] },
      { id: 'revasc_required_pre_aorta', label: 'Rewaskularyzacja wymagana przed naprawą aorty', type: FieldType.RADIO, options: YES_NO_UNKNOWN }
    ]
  },
  {
    id: 'sec_g_proc',
    title: 'Sekcja G: Dane Proceduralne',
    description: 'Szczegóły zabiegu i konfiguracja v1.1',
    fields: [
      { id: 'hdr_g_basic', label: 'CZAS I WARUNKI', type: FieldType.SECTION_HEADER },
      { id: 'proc_date', label: 'Data zabiegu', type: FieldType.DATE },
      { id: 'urgency_proc', label: 'Tryb zabiegu', type: FieldType.RADIO, options: [{label: 'Planowy', value: 'elective'}, {label: 'Pilny (<24h)', value: 'urgent'}, {label: 'Nagły (<2h)', value: 'emergency'}, {label: 'Ratunkowy', value: 'salvage'}] },
      { id: 'proc_location', label: 'Miejsce zabiegu', type: FieldType.RADIO, options: [{label: 'Hybrydowa sala operacyjna', value: 'hybrid'}, {label: 'Konwencjonalna sala oper.', value: 'conv'}] },
      { id: 'operator_1_init', label: 'Operator 1 (inicjały)', type: FieldType.TEXT },
      { id: 'operator_2_init', label: 'Operator 2 (inicjały)', type: FieldType.TEXT },
      { id: 'hdr_g_access', label: 'DOSTĘP NACZYNIOWY', type: FieldType.SECTION_HEADER },
      { id: 'main_access', label: 'Główny dostęp tętniczy', type: FieldType.SELECT, options: [{label: 'Femoral R', value: 'fem_r'}, {label: 'Femoral L', value: 'fem_l'}, {label: 'Konduit biodrowy', value: 'conduit'}, {label: 'Aortalny', value: 'aortal'}] },
      { id: 'main_sheath_fr', label: 'Rozmiar koszulki głównej (Fr)', type: FieldType.NUMBER },
      { id: 'add_access_site', label: 'Dostępy dodatkowe', type: FieldType.CHECKBOX, options: [{label: 'T. skroniowa pow. R', value: 'temporal_r'}, {label: 'T. skroniowa pow. L', value: 'temporal_l'}, {label: 'T. podobojczykowa R', value: 'subclavian_r'}, {label: 'T. szyjna wspólna L', value: 'carotid_l'}, {label: 'Promieniowy R', value: 'rad_r'}, {label: 'Promieniowy L', value: 'rad_l'}, {label: 'Ramienny R', value: 'brach_r'}, {label: 'Ramienny L', value: 'brach_l'}, {label: 'Pachowy R', value: 'ax_r'}, {label: 'Pachowy L', value: 'ax_l'}] },
      { id: 'hdr_g_config', label: 'KONFIGURACJA URZĄDZENIA', type: FieldType.SECTION_HEADER },
      { id: 'stentgraft_system', label: 'System stentgraftu', type: FieldType.SELECT, options: [{label: 'NEXUS', value: 'nexus'}, {label: 'COOK arch branch', value: 'cook'}, {label: 'RelayBranch', value: 'relay'}, {label: 'Gore TAG', value: 'gore'}, {label: 'Inny', value: 'other'}] },
      { id: 'stentgraft_size', label: 'Rozmiar głównego stentgraftu', type: FieldType.TEXT, placeholder: 'np. 40-28-32/221' },
      { id: 'nexus_config', label: 'Konfiguracja NEXUS', type: FieldType.SELECT, options: [{label: 'LIFS (LCCA & LSA)', value: 'lifs_lcca_lsa'}, {label: 'LIFS (LCCA)', value: 'lifs_lcca'}] },
      { id: 'cook_config', label: 'Konfiguracja COOK', type: FieldType.SELECT, options: [{label: '3 AB', value: '3ab'}, {label: '2 AB', value: '2ab'}, {label: 'CMD Branch/Fen (LCCA & LSA)', value: 'cmd_lcca_lsa'}, {label: '3 AB retrograde (LCCA & LSA)', value: '3ab_retro_lcca_lsa'}, {label: '3 AB retrograde (BCT & LCCA & LSA)', value: '3ab_retro_bct_lcca_lsa'}] },
      { id: 'hdr_g_cook_detail', label: 'Szczegółowa konfiguracja COOK', type: FieldType.SECTION_HEADER },
      { id: 'cook_lsa_strategy', label: 'LSA - strategia leczenia', type: FieldType.RADIO, options: [{label: 'Retrograde branch', value: 'retro'}, {label: 'Antegrade branch', value: 'ante'}, {label: 'FEN', value: 'fen'}, {label: 'Nie leczono', value: 'not_treated'}] },
      { id: 'cook_lcca_strategy', label: 'LCCA - strategia leczenia', type: FieldType.RADIO, options: [{label: 'Retrograde branch', value: 'retro'}, {label: 'Antegrade branch', value: 'ante'}, {label: 'FEN', value: 'fen'}, {label: 'SCALLOP', value: 'scallop'}, {label: 'Nie leczono', value: 'not_treated'}] },
      { id: 'cook_bct_strategy', label: 'BCT - strategia leczenia', type: FieldType.RADIO, options: [{label: 'Retrograde branch', value: 'retro'}, {label: 'Antegrade branch', value: 'ante'}, {label: 'SCALLOP', value: 'scallop'}, {label: 'Nie leczono', value: 'not_treated'}] },
      { id: 'bct_order', label: 'BCT - kolejność', type: FieldType.NUMBER },
      { id: 'lcca_order', label: 'LCCA - kolejność', type: FieldType.NUMBER },
      { id: 'lsa_order', label: 'LSA - kolejność', type: FieldType.NUMBER },
      { id: 'hdr_g_bct_stents', label: 'BCT - stenty (możliwość wpisania wielu)', type: FieldType.SECTION_HEADER },
      { id: 'bct_stent1_type', label: 'BCT stent 1 - typ', type: FieldType.SELECT, options: [{label: 'CMD', value: 'cmd'}, {label: 'VBX', value: 'vbx'}, {label: 'BGP+', value: 'bgp'}, {label: 'ZILVER', value: 'zilver'}, {label: 'Inny', value: 'other'}] },
      { id: 'bct_stent1_diam', label: 'BCT stent 1 - rozmiar (śr)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'bct_stent1_len', label: 'BCT stent 1 - rozmiar (dł)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'bct_stent2_type', label: 'BCT stent 2 - typ', type: FieldType.SELECT, options: [{label: 'CMD', value: 'cmd'}, {label: 'VBX', value: 'vbx'}, {label: 'BGP+', value: 'bgp'}, {label: 'ZILVER', value: 'zilver'}, {label: 'Inny', value: 'other'}] },
      { id: 'bct_stent2_diam', label: 'BCT stent 2 - rozmiar (śr)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'bct_stent2_len', label: 'BCT stent 2 - rozmiar (dł)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'bct_stent3_type', label: 'BCT stent 3 - typ', type: FieldType.SELECT, options: [{label: 'VBX', value: 'vbx'}, {label: 'BGP+', value: 'bgp'}, {label: 'ZILVER', value: 'zilver'}, {label: 'Inny', value: 'other'}, {label: 'N/D', value: 'nd'}] },
      { id: 'bct_stent3_diam', label: 'BCT stent 3 - rozmiar (śr)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'bct_stent3_len', label: 'BCT stent 3 - rozmiar (dł)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'hdr_g_lcca_stents', label: 'LCCA - stenty (możliwość wpisania wielu)', type: FieldType.SECTION_HEADER },
      { id: 'lcca_stent1_type', label: 'LCCA stent 1 - typ', type: FieldType.SELECT, options: [{label: 'VBX', value: 'vbx'}, {label: 'BGP+', value: 'bgp'}, {label: 'ZILVER', value: 'zilver'}, {label: 'Inny', value: 'other'}] },
      { id: 'lcca_stent1_diam', label: 'LCCA stent 1 - rozmiar (śr)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'lcca_stent1_len', label: 'LCCA stent 1 - rozmiar (dł)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'lcca_stent2_type', label: 'LCCA stent 2 - typ', type: FieldType.SELECT, options: [{label: 'VBX', value: 'vbx'}, {label: 'BGP+', value: 'bgp'}, {label: 'ZILVER', value: 'zilver'}, {label: 'Inny', value: 'other'}, {label: 'N/D', value: 'nd'}] },
      { id: 'lcca_stent2_diam', label: 'LCCA stent 2 - rozmiar (śr)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'lcca_stent2_len', label: 'LCCA stent 2 - rozmiar (dł)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'lcca_stent3_type', label: 'LCCA stent 3 - typ', type: FieldType.SELECT, options: [{label: 'VBX', value: 'vbx'}, {label: 'BGP+', value: 'bgp'}, {label: 'ZILVER', value: 'zilver'}, {label: 'Inny', value: 'other'}, {label: 'N/D', value: 'nd'}] },
      { id: 'lcca_stent3_diam', label: 'LCCA stent 3 - rozmiar (śr)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'lcca_stent3_len', label: 'LCCA stent 3 - rozmiar (dł)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'hdr_g_lsa_stents', label: 'LSA - stenty (możliwość wpisania wielu)', type: FieldType.SECTION_HEADER },
      { id: 'lsa_stent1_type', label: 'LSA stent 1 - typ', type: FieldType.SELECT, options: [{label: 'VBX', value: 'vbx'}, {label: 'BGP+', value: 'bgp'}, {label: 'ZILVER', value: 'zilver'}, {label: 'Inny', value: 'other'}] },
      { id: 'lsa_stent1_diam', label: 'LSA stent 1 - rozmiar (śr)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'lsa_stent1_len', label: 'LSA stent 1 - rozmiar (dł)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'lsa_stent2_type', label: 'LSA stent 2 - typ', type: FieldType.SELECT, options: [{label: 'VBX', value: 'vbx'}, {label: 'BGP+', value: 'bgp'}, {label: 'ZILVER', value: 'zilver'}, {label: 'Inny', value: 'other'}, {label: 'N/D', value: 'nd'}] },
      { id: 'lsa_stent2_diam', label: 'LSA stent 2 - rozmiar (śr)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'lsa_stent2_len', label: 'LSA stent 2 - rozmiar (dł)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'lsa_stent3_type', label: 'LSA stent 3 - typ', type: FieldType.SELECT, options: [{label: 'VBX', value: 'vbx'}, {label: 'BGP+', value: 'bgp'}, {label: 'ZILVER', value: 'zilver'}, {label: 'Inny', value: 'other'}, {label: 'N/D', value: 'nd'}] },
      { id: 'lsa_stent3_diam', label: 'LSA stent 3 - rozmiar (śr)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'lsa_stent3_len', label: 'LSA stent 3 - rozmiar (dł)', type: FieldType.NUMBER, unit: 'mm' },
      { id: 'total_stents_implanted', label: 'Całkowita liczba stentów implantowanych', type: FieldType.NUMBER },
      { id: 'proc_config', label: 'Konfiguracja', type: FieldType.RADIO, options: [{label: 'Rozgałęziony (branched)', value: 'branched'}, {label: 'Modułowy', value: 'modular'}, {label: 'Fenestrowany', value: 'fen'}, {label: 'LIFS', value: 'lifs'}] },
      { id: 'treated_arch_branches_count', label: 'Liczba leczonych odgałęzień łuku', type: FieldType.RADIO, options: [{label: '1', value: '1'}, {label: '2', value: '2'}, {label: '3', value: '3'}] },
      { id: 'treated_vessels', label: 'Leczone naczynia', type: FieldType.SELECT, options: [{label: 'BCT/Pień r-g', value: 'bct'}, {label: 'LCCA', value: 'lcca'}, {label: 'LSA', value: 'lsa'}, {label: 'Wiele', value: 'multi'}] },
      { id: 'lsa_coverage_no_revasc', label: 'Pokrycie LSA bez rewaskularyzacji', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'bypass_cs_p', label: 'Bypass/transpozycja szyjno-podobojczykowa', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_g_staging', label: 'ETAPOWANIE LECZENIA - SEKWENCJA ZABIEGÓW', type: FieldType.SECTION_HEADER },
      { id: 'treatment_type', label: 'Typ leczenia', type: FieldType.CHECKBOX, options: [{label: 'TEVAR', value: 'tevar'}, {label: 'BEVAR', value: 'bevar'}, {label: 'fEVAR', value: 'fevar'}, {label: 'EVAR', value: 'evar'}, {label: 'IBD Iliac SG', value: 'ibd_iliac_sg'}] },
      { id: 'pre_ab_stentgraft_yn', label: 'Czy implantowano stentgraft przed Arch Branch', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'pre_ab_procedure_date', label: 'Data zabiegu poprzedzającego', type: FieldType.DATE },
      { id: 'pre_ab_procedure_type', label: 'Typ zabiegu przed AB', type: FieldType.SELECT, options: [{label: 'TEVAR', value: 'tevar'}, {label: 'BEVAR', value: 'bevar'}, {label: 'fEVAR', value: 'fevar'}, {label: 'EVAR', value: 'evar'}, {label: 'IBD', value: 'ibd'}, {label: 'Inny', value: 'other'}] },
      { id: 'pre_ab_procedure_notes', label: 'Uwagi dot. zabiegu przed AB', type: FieldType.TEXTAREA },
      { id: 'during_ab_stentgraft_yn', label: 'Czy implantowano dodatkowy stentgraft podczas AB', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'during_ab_procedure_type', label: 'Typ dodatkowego zabiegu podczas AB', type: FieldType.SELECT, options: [{label: 'TEVAR', value: 'tevar'}, {label: 'BEVAR', value: 'bevar'}, {label: 'fEVAR', value: 'fevar'}, {label: 'EVAR', value: 'evar'}, {label: 'IBD', value: 'ibd'}, {label: 'Inny', value: 'other'}] },
      { id: 'during_ab_procedure_notes', label: 'Uwagi dot. dodatkowego zabiegu', type: FieldType.TEXTAREA },
      { id: 'post_ab_planned_yn', label: 'Czy planowany kolejny etap leczenia po AB', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'post_ab_procedure_date', label: 'Data planowanego / wykonanego zabiegu po AB', type: FieldType.DATE },
      { id: 'post_ab_procedure_type', label: 'Typ zabiegu po AB', type: FieldType.CHECKBOX, options: [{label: 'TEVAR', value: 'tevar'}, {label: 'BEVAR', value: 'bevar'}, {label: 'fEVAR', value: 'fevar'}, {label: 'EVAR', value: 'evar'}, {label: 'IBD Iliac SG', value: 'ibd_iliac_sg'}] },
      { id: 'post_ab_procedure_status', label: 'Status zabiegu po AB', type: FieldType.RADIO, options: [{label: 'Planowany', value: 'planned'}, {label: 'Wykonany', value: 'executed'}, {label: 'Odwołany', value: 'cancelled'}, {label: 'N/D', value: 'nd'}] },
      { id: 'post_ab_procedure_notes', label: 'Uwagi dot. zabiegu po AB', type: FieldType.TEXTAREA }
    ]
  },
  {
    id: 'sec_g2_matasa',
    title: '[Nowe] Sekcja G2: Próba Matasa (dla LIFS/NEXUS)',
    description: 'Ocena tolerancji ucisku t. szyjnej v1.1',
    fields: [
      { id: 'matasa_done', label: 'Wykonano próbę Matasa', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'matasa_compression_time', label: 'Czas ucisku t. szyjnej (minuty)', type: FieldType.NUMBER },
      { id: 'matasa_side', label: 'Strona ucisku', type: FieldType.RADIO, options: [{label: 'Prawa', value: 'r'}, {label: 'Lewa', value: 'l'}, {label: 'Obustronna (sekwencyjnie)', value: 'both'}] },
      { id: 'matasa_neuro_symptoms', label: 'Objawy neurologiczne podczas próby', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'matasa_symptoms_desc', label: 'Jeśli objawy - opis', type: FieldType.TEXTAREA },
      { id: 'matasa_rso2_drop_detected', label: 'Spadek rSO2 podczas próby Matasa', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'matasa_rso2_drop_max', label: 'Maks. spadek rSO2 podczas próby (%)', type: FieldType.NUMBER, unit: '%' },
      { id: 'matasa_result', label: 'Wynik próby Matasa', type: FieldType.SELECT, options: [{label: 'Negatywna (toleruje)', value: 'neg'}, {label: 'Pozytywna (nietolerancja)', value: 'pos'}, {label: 'Nieokreślona', value: 'unclear'}] },
      { id: 'lifs_reason', label: 'Uzasadnienie zastosowania LIFS', type: FieldType.SELECT, options: [{label: 'Anatomia naczyń', value: 'anat'}, {label: 'Ograniczenia urządzenia', value: 'device'}, {label: 'Kąt odejścia naczynia', value: 'angle'}, {label: 'Odległość między tt.', value: 'dist'}, {label: 'Inne', value: 'inne'}] }
    ]
  },
  {
    id: 'sec_h_hemo',
    title: 'Sekcja H: Śródoperacyjne Monitorowanie i Hemodynamika',
    description: 'NIRS i parametry hemodynamiczne v1.1',
    fields: [
      { id: 'hdr_h_nirs', label: 'MONITOROWANIE NIRS (SPEKTROSKOPIA)', type: FieldType.SECTION_HEADER },
      { id: 'nirs_used', label: 'Stosowano monitorowanie NIRS', type: FieldType.RADIO, options: YES_NO },
      { id: 'nirs_device', label: 'Urządzenie NIRS', type: FieldType.TEXT },
      { id: 'rso2_baseline_r', label: 'Wyjściowe rSO2 (prawa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_baseline_l', label: 'Wyjściowe rSO2 (lewa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_lowest_r', label: 'Najniższe rSO2 (prawa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_lowest_l', label: 'Najniższe rSO2 (lewa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_delta_max_r', label: 'Maks. Delta rSO2 (prawa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_delta_max_l', label: 'Maks. Delta rSO2 (lewa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_alert_triggered', label: 'Wyzwolono alert rSO2 (spadek >20% lub <50% bezwzgl.)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'rso2_intervention', label: 'Wywolano interwencje rSO2 (spadek >25% lub <40%)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_h_nirs_phases', label: '[NOWE] NIRS PODCZAS KLUCZOWYCH FAZ ZABIEGU', type: FieldType.SECTION_HEADER },
      { id: 'rso2_pre_stim_r', label: 'rSO2 przed stymulacją (prawa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_pre_stim_l', label: 'rSO2 przed stymulacją (lewa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_during_stim_r', label: 'rSO2 podczas stymulacji (prawa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_during_stim_l', label: 'rSO2 podczas stymulacji (lewa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_at_deployment_r', label: 'rSO2 przy rozprężeniu (prawa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'rso2_at_deployment_l', label: 'rSO2 przy rozprężeniu (lewa)', type: FieldType.NUMBER, unit: '%' },
      { id: 'hdr_h_map', label: 'STREFA KONTROLI MAP (CEL: 80-100 mmHg)', type: FieldType.SECTION_HEADER },
      { id: 'map_baseline', label: 'Wyjściowe MAP', type: FieldType.NUMBER, unit: 'mmHg' },
      { id: 'map_highest', label: 'Najwyższe MAP', type: FieldType.NUMBER, unit: 'mmHg' },
      { id: 'map_lowest', label: 'Najniższe MAP', type: FieldType.NUMBER, unit: 'mmHg' },
      { id: 'map_at_deployment', label: 'MAP przy rozprężeniu', type: FieldType.NUMBER, unit: 'mmHg' },
      { id: 'map_lt_80_time', label: 'Czas MAP <80 mmHg (minuty)', type: FieldType.NUMBER },
      { id: 'map_gt_100_time', label: 'Czas MAP >100 mmHg (minuty)', type: FieldType.NUMBER },
      { id: 'map_ge_85_pre_stim', label: 'MAP >=85 mmHg przez >=30s przed stymulacją', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_h_hr_reduction', label: 'TECHNIKI REDUKCJI RZUTU SERCA', type: FieldType.SECTION_HEADER },
      { id: 'hr_reduction_method', label: 'Metoda kontroli rzutu serca', type: FieldType.RADIO, options: [{label: 'Brak (MAP stabilne)', value: 'none'}, {label: 'Rapid ventricular pacing', value: 'rvp'}, {label: 'Manewr Valsalvy', value: 'valsalva'}, {label: 'IVC balloon occlusion', value: 'ivc_balloon'}] },
      { id: 'map_pre_stentgraft', label: 'MAP przed włożeniem stentgraftu (jeśli bez stymulacji)', type: FieldType.NUMBER, unit: 'mmHg' },
      { id: 'map_post_stentgraft', label: 'MAP po włożeniu stentgraftu', type: FieldType.NUMBER, unit: 'mmHg' },
      { id: 'pacing_abandoned_reason', label: 'Uzasadnienie odstąpienia od stymulacji (jeśli brak)', type: FieldType.TEXTAREA },
      { id: 'hdr_h_wentylacja', label: 'WENTYLACJA I PERFUZJA', type: FieldType.SECTION_HEADER },
      { id: 'etco2_target_maintained', label: 'Cel EtCO2 (35-40 mmHg) utrzymany', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'paco2_measured', label: 'PaCO2 (jeśli mierzono)', type: FieldType.NUMBER, unit: 'mmHg' },
      { id: 'lowest_body_temp', label: 'Temperatura (najniższa)', type: FieldType.NUMBER, unit: '°C' },
      { id: 'hdr_h_anticoag', label: 'ANTYKOAGULACJA', type: FieldType.SECTION_HEADER },
      { id: 'heparin_dose_total', label: 'Dawka heparyny (j.m.)', type: FieldType.NUMBER },
      { id: 'baseline_act', label: 'ACT (sekundy) po podaniu Heparyny', type: FieldType.NUMBER },
      { id: 'peak_act', label: 'Szczytowy ACT (sekundy)', type: FieldType.NUMBER },
      { id: 'act_target_maintained', label: 'ACT utrzymany 250-300s przez cały zabieg', type: FieldType.RADIO, options: YES_NO },
      { id: 'protamine_given', label: 'Podano protaminę', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'protamine_dose', label: 'Dawka protaminy (mg)', type: FieldType.NUMBER },
      { id: 'hdr_h_pacing', label: 'SZYBKA STYMULACJA KOMOROWA (RAPID PACING)', type: FieldType.SECTION_HEADER },
      { id: 'rapid_pacing_used', label: 'Stosowano szybką stymulację komorową', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'pacing_episodes_count', label: 'Liczba epizodów stymulacji', type: FieldType.NUMBER },
      { id: 'pacing_time_total', label: 'Całkowity czas stymulacji (sekundy)', type: FieldType.NUMBER },
      { id: 'pacing_freq', label: 'Częstość stymulacji (/min)', type: FieldType.NUMBER },
      { id: 'volume_filling_pre_stim', label: 'Wypełnienie objętościowe przed stymulacją (mL)', type: FieldType.NUMBER }
    ]
  },
  {
    id: 'sec_i_protection',
    title: 'Sekcja I: Ochrona przed Zatorami i Płukanie Urządzenia',
    description: 'Strategie protekcji v1.1',
    fields: [
      { id: 'hdr_i_flush', label: 'CIĄGŁE PŁUKANIE KOSZULKI', type: FieldType.SECTION_HEADER },
      { id: 'continuous_flush_used', label: 'Stosowano ciągłe płukanie solą heparynizowaną', type: FieldType.RADIO, options: YES_NO },
      { id: 'flush_fluid_type', label: 'Roztwór do płukania', type: FieldType.SELECT, options: [{label: '0,9% NaCl + 1000 j.m. heparyny/L', value: 'std'}, {label: 'Inny', value: 'other'}] },
      { id: 'flush_pressure_target', label: 'Ciśnienie w worku 150-200 mmHg', type: FieldType.RADIO, options: YES_NO },
      { id: 'flush_rate_drops_per_sec', label: 'Prędkość płukania (kropli/sekundę)', type: FieldType.NUMBER, unit: 'cel: 1-2' },
      { id: 'hdr_i_prep', label: 'WSTĘPNE PŁUKANIE STENTGRAFTU', type: FieldType.SECTION_HEADER },
      { id: 'sg_flush_technique', label: 'Technika płukania stentgraftu', type: FieldType.SELECT, options: [{label: 'CO2 + sol fizjol. (w koszulce)', value: 'co2_sal'}, {label: 'Sol fizjologiczna (sama)', value: 'saline_only'}, {label: 'Wypływ wsteczny (w rękawie)', value: 'retro'}, {label: 'Inna', value: 'other'}] },
      { id: 'sg_air_removed_confirmed', label: 'Potwierdzono całkowite usunięcie powietrza', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_i_epd', label: 'DYSTALNA OCHRONA ZATOROWA (EPD)', type: FieldType.SECTION_HEADER },
      { id: 'epd_used_proc', label: 'Stosowano dystalną ochronę zatorową (EPD)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'epd_indication', label: 'Wskazanie do EPD', type: FieldType.SELECT, options: [{label: 'Aorta shaggy', value: 'shaggy'}, {label: 'Skrzeplina łuku', value: 'thromb_arch'}, {label: 'Skrzeplina aorty wstęp.', value: 'thromb_asc'}, {label: 'Rutynowo', value: 'routine'}, {label: 'Inne', value: 'other'}] },
      { id: 'epd_device', label: 'Urządzenie ochronne', type: FieldType.SELECT, options: [{label: 'Filtr Spider', value: 'spider'}, {label: 'Sentinel', value: 'sentinel'}, {label: 'TriGuard', value: 'triguard'}, {label: 'Inne', value: 'other'}] },
      { id: 'epd_protected_vessels', label: 'Chronione naczynia', type: FieldType.SELECT, options: [{label: 'Prawa CCA (przez BCT)', value: 'r_cca'}, {label: 'LCCA', value: 'lcca'}, {label: 'Obie CCA', value: 'both'}] },
      { id: 'epd_access_site', label: 'Dostęp dla EPD', type: FieldType.SELECT, options: [{label: 'Promieniowy prawy', value: 'rad_r'}, {label: 'Promieniowy lewy', value: 'rad_l'}, {label: 'Ramienny', value: 'brach'}, {label: 'Udowy', value: 'fem'}] },
      { id: 'epd_sheath_fr', label: 'Rozmiar koszulki ochronnej (Fr)', type: FieldType.NUMBER },
      { id: 'epd_removed_success', label: 'Filtr pomyślnie usunięty', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'epd_material_visible', label: 'Widoczny materiał zatorowy w filtrze', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'epd_material_desc', label: 'Opis materiału (jeśli widoczny)', type: FieldType.TEXTAREA },
      { id: 'epd_to_pathology', label: 'Filtr wysłany do badania histopatologicznego', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_i_analysis', label: '[NOWE] ANALIZA MATERIAŁU ZATOROWEGO', type: FieldType.SECTION_HEADER },
      { id: 'epd_material_type', label: 'Typ materiału', type: FieldType.SELECT, options: [{label: 'Skrzeplina', value: 'thrombus'}, {label: 'Blaszka miażdż.', value: 'plaque'}, {label: 'Materiał mieszany', value: 'mixed'}, {label: 'Inne', value: 'other'}] },
      { id: 'epd_material_vol_mm3', label: 'Szacowana objętość materiału (mm3)', type: FieldType.NUMBER },
      { id: 'epd_ct_correlation', label: 'Korelacja z obrazem TK (shaggy/skrzeplina)', type: FieldType.RADIO, options: YES_NO_UNKNOWN }
    ]
  },
  {
    id: 'sec_j_completion',
    title: 'Sekcja J: Zakończenie Zabiegu',
    description: 'Wyniki techniczne v1.1',
    fields: [
      { id: 'hdr_j_awakening_or', label: 'WYBUDZENIE PACJENTA NA SALI OPERACYJNEJ', type: FieldType.SECTION_HEADER },
      { id: 'verbal_contact_or', label: 'Kontakt słowno-logiczny na sali', type: FieldType.RADIO, options: [{label: 'Tak - w kontakcie', value: 'yes'}, {label: 'Nie - brak kontaktu', value: 'no'}] },
      { id: 'motor_deficit_or', label: 'Niedowład kończyn na sali', type: FieldType.RADIO, options: [{label: 'Brak', value: 'none'}, {label: 'Obecny - KG', value: 'kg'}, {label: 'Obecny - KD', value: 'kd'}, {label: 'Obecny - obie strony', value: 'both'}] },
      { id: 'neuro_notes_or', label: 'Uwagi dot. stanu neurologicznego na sali', type: FieldType.TEXTAREA },
      { id: 'hdr_j_awakening_icu', label: 'WYBUDZENIE PACJENTA NA OITCH', type: FieldType.SECTION_HEADER },
      { id: 'awakening_time_icu', label: 'Godzina wybudzenia na OITCH', type: FieldType.TIME },
      { id: 'time_to_awakening_hours', label: 'Czas od końca zabiegu do wybudzenia (godzin)', type: FieldType.NUMBER },
      { id: 'verbal_contact_icu', label: 'Kontakt słowno-logiczny na OITCH', type: FieldType.RADIO, options: [{label: 'Tak - w kontakcie', value: 'yes'}, {label: 'Nie - brak kontaktu', value: 'no'}] },
      { id: 'motor_deficit_icu', label: 'Niedowład kończyn na OITCH', type: FieldType.RADIO, options: [{label: 'Brak', value: 'none'}, {label: 'Obecny - KG', value: 'kg'}, {label: 'Obecny - KD', value: 'kd'}, {label: 'Obecny - obie strony', value: 'both'}] },
      { id: 'gcs_icu', label: 'GCS przy wybudzeniu na OITCH', type: FieldType.NUMBER, unit: '/15' },
      { id: 'neuro_notes_icu', label: 'Uwagi dot. stanu neurologicznego na OITCH', type: FieldType.TEXTAREA },
      { id: 'hdr_j_params', label: 'PARAMETRY ZABIEGU', type: FieldType.SECTION_HEADER },
      { id: 'fluoro_time_min', label: 'Czas fluoroskopii (min)', type: FieldType.NUMBER },
      { id: 'contrast_vol_ml', label: 'Objętość kontrastu (mL)', type: FieldType.NUMBER },
      { id: 'est_blood_loss_ml', label: 'Szacowana utrata krwi (mL)', type: FieldType.NUMBER },
      { id: 'intraop_angio_neuro_done', label: 'Wykonano angiografię wewnątrzczaszkową', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'intraop_angio_neuro_result', label: 'Stan naczyń w angio (jeśli tak)', type: FieldType.SELECT, options: [{label: 'Wszystkie drożne', value: 'patent'}, {label: 'Wykryto niedrożność', value: 'occl'}] },
      { id: 'hdr_j_success', label: 'WYNIK TECHNICZNY', type: FieldType.SECTION_HEADER },
      { id: 'tech_success', label: 'Sukces techniczny (ekskluzja, drożność, brak I/III)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'endoleak_type_1', label: 'Przeciek typu I', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'endoleak_type_2', label: 'Przeciek typu II', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'endoleak_type_3', label: 'Przeciek typu III', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'branch_vessel_occlusion', label: 'Niedrożność naczynia odgałęzionego', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'open_conversion', label: 'Konwersja do operacji otwartej', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'unplanned_addon_proc', label: 'Nieplanowany dodatkowy zabieg', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_j_limits', label: '[NOWE] OGRANICZENIA TECHNICZNE URZĄDZENIA', type: FieldType.SECTION_HEADER },
      { id: 'tech_limit_encountered', label: 'Napotkano ograniczenia techniczne urządzenia', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'tech_limit_type', label: 'Typ ograniczenia', type: FieldType.SELECT, options: [{label: 'Rozmiar (maks. 46mm)', value: 'size'}, {label: 'Kąt odejścia', value: 'angle'}, {label: 'Długość', value: 'length'}, {label: 'Inne', value: 'other'}] },
      { id: 'tech_limit_desc', label: 'Opis ograniczenia', type: FieldType.TEXTAREA }
    ]
  },
  {
    id: 'sec_k_neuro_outcome',
    title: 'Sekcja K: Wyniki Neurologiczne',
    description: 'Ocena powikłań v1.1 - ROZSZERZONA',
    fields: [
      { id: 'hdr_k_immediate', label: 'BEZPOŚREDNIA OCENA POOPERACYJNA (W CIĄGU 24H)', type: FieldType.SECTION_HEADER },
      { id: 'new_neuro_deficit_at_wake', label: 'Nowy ogniskowy deficyt neurologiczny przy wybudzeniu', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'time_to_first_neuro_eval_h', label: 'Czas pierwszej oceny neurologicznej (h po zabiegu)', type: FieldType.NUMBER },
      { id: 'gcs_at_wake', label: 'GCS przy wybudzeniu', type: FieldType.NUMBER, unit: '/15' },
      { id: 'motor_deficit', label: 'Deficyt ruchowy (jakikolwiek)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'speech_deficit', label: 'Deficyt mowy/języka', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'vision_deficit', label: 'Deficyt wzrokowy', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_k_stroke_30d', label: 'UDAR (W CIĄGU 30 DNI)', type: FieldType.SECTION_HEADER },
      { id: 'any_stroke_30d', label: 'Jakikolwiek udar', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'stroke_date', label: 'Jeśli tak - data wystąpienia', type: FieldType.DATE },
      { id: 'stroke_time_from_proc_h', label: 'Czas od zabiegu do udaru (godziny)', type: FieldType.NUMBER },
      { id: 'stroke_type_cat', label: 'Typ udaru', type: FieldType.SELECT, options: [{label: 'Niedokrwienny', value: 'isch'}, {label: 'Krwotoczny', value: 'hem'}, {label: 'Oba/mieszany', value: 'mix'}, {label: 'Nieznany', value: 'unk'}] },
      { id: 'stroke_area_cat', label: 'Obszar udaru', type: FieldType.SELECT, options: [{label: 'MCA', value: 'mca'}, {label: 'ACA', value: 'aca'}, {label: 'PCA', value: 'pca'}, {label: 'Kręgowo-podstawny', value: 'vb'}, {label: 'Strefowy (watershed)', value: 'ws'}, {label: 'Liczne', value: 'multi'}, {label: 'Nieznany', value: 'unk'}] },
      { id: 'stroke_side', label: 'Strona udaru', type: FieldType.RADIO, options: [{label: 'Prawa', value: 'r'}, {label: 'Lewa', value: 'l'}, {label: 'Obustronna', value: 'bilat'}] },
      { id: 'stroke_imaging_confirmed', label: 'Potwierdzenie obrazowe (TK/MR)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'nihss_at_diagnosis', label: 'NIHSS przy rozpoznaniu', type: FieldType.NUMBER, unit: '/42' },
      { id: 'mrs_at_30d', label: 'mRS w 30. dobie', type: FieldType.NUMBER, unit: '/6' },
      { id: 'stroke_classification_30d', label: 'Klasyfikacja udaru', type: FieldType.SELECT, options: [{label: 'Mały (mRS 0-2)', value: 'small'}, {label: 'Duży (mRS 3-5)', value: 'large'}, {label: 'Śmiertelny (mRS 6)', value: 'fatal'}] },
      { id: 'hdr_k_correlation', label: '[NOWE] KORELACJA Z CZYNNIKAMI RYZYKA', type: FieldType.SECTION_HEADER },
      { id: 'corr_asc_aorta_ge_40', label: 'Udar u pacjenta z śr. aorty wstęp. >36 mm', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'corr_prev_stroke_tia', label: 'Udar u pacjenta z przebytym udarem/TIA', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'corr_shaggy_aorta', label: 'Udar u pacjenta z aortą shaggy', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'corr_willis_inc', label: 'Udar u pacjenta z niepełnym Kołem Willisa', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'corr_aneurysm_ge_70', label: 'Udar u pacjenta z tętniakiem >= 70 mm', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_k_tia', label: 'PRZEMIJAJĄCY ATAK NIEDOKRWIENNY (TIA)', type: FieldType.SECTION_HEADER },
      { id: 'tia_any', label: 'TIA (deficyt <24h, brak zmian w TK/MR)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'tia_date', label: 'Data TIA', type: FieldType.DATE },
      { id: 'tia_duration_h', label: 'Czas trwania objawów (h)', type: FieldType.NUMBER },
      { id: 'tia_symptoms', label: '[NOWE] Objawy TIA', type: FieldType.SELECT, options: [{label: 'Niedowlad', value: 'weak'}, {label: 'Zaburzenia mowy', value: 'speech'}, {label: 'Zaburzenia widzenia', value: 'vision'}, {label: 'Zawroty głowy', value: 'dizz'}, {label: 'Inne', value: 'other'}] },
      { id: 'hdr_k_sci', label: 'NIEDOKRWIENIE RDZENIA KRĘGOWEGO (SCI)', type: FieldType.SECTION_HEADER },
      { id: 'sci_any', label: 'Niedokrwienie rdzenia kręgowego', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'sci_severity', label: 'Nasilenie SCI', type: FieldType.SELECT, options: [{label: 'Niedowład kończyn dolnych', value: 'weak'}, {label: 'Porażenie kończyn dolnych', value: 'paral'}, {label: 'Przemijające (ustąpiło)', value: 'trans'}] },
      { id: 'sci_onset_h_post_proc', label: 'Czas do wystąpienia objawów (h po zabiegu)', type: FieldType.NUMBER },
      { id: 'hdr_k_intervention', label: 'INTERWENCJA NEURONACZYNIOWA', type: FieldType.SECTION_HEADER },
      { id: 'thrombectomy_done', label: 'Wykonano trombektomię mechaniczną', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'thrombectomy_time_to_puncture', label: 'Czas od objawów do nakłucia (min)', type: FieldType.NUMBER },
      { id: 'thrombectomy_recanalization', label: 'Skuteczna rekanalizacja (TICI 2b/3)', type: FieldType.RADIO, options: YES_NO_UNKNOWN }
    ]
  },
  {
    id: 'sec_l_complications',
    title: 'Sekcja L: Inne Powikłania (30-dniowe)',
    description: 'Powikłania ogólnoustrojowe v1.1',
    fields: [
      { id: 'hdr_l_cv', label: 'SERCOWO-NACZYNIOWE', type: FieldType.SECTION_HEADER },
      { id: 'mi_30d', label: 'Zawał mięśnia sercowego', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'afib_new_onset', label: 'Nowo powstałe migotanie przedsionków', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'cardiac_arrest', label: 'Zatrzymanie krążenia', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'aortic_rupture_post', label: 'Pęknięcie aorty', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'retrograde_type_a', label: 'Wsteczne rozwarstwienie typu A', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_l_access', label: 'DOSTĘP NACZYNIOWY', type: FieldType.SECTION_HEADER },
      { id: 'access_hematoma', label: 'Krwiak w miejscu dostępu', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'access_hematoma_intervention', label: 'Krwiak w miejscu dostępu wymagający interwencji', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'retroperitoneal_hematoma', label: 'Krwiak zaotrzewnowy', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'av_fistula', label: 'Przetoka tętniczo-żylna', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'limb_ischemia_major', label: 'Niedokrwienie kończyny', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_l_local', label: 'POWIKŁANIA MIEJSCOWE', type: FieldType.SECTION_HEADER },
      { id: 'pseudoaneurysm', label: 'Tętniak rzekomy', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'av_fistula_temporal', label: 'Przetoka t-z po dostępie skroniowym', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_l_renal', label: 'NERKOWE', type: FieldType.SECTION_HEADER },
      { id: 'aki_akin_ge_2', label: 'Ostre uszkodzenie nerek (AKIN >=2)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'new_dialysis_required', label: 'Nowa konieczność dializy', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_l_resp', label: 'ODDECHOWE', type: FieldType.SECTION_HEADER },
      { id: 'pneumonia_30d', label: 'Zapalenie płuc', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'vent_gt_48h', label: 'Przedłużona wentylacja (>48h)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'tracheostomy_required', label: 'Tracheostomia', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_l_inf', label: 'INFEKCYJNE', type: FieldType.SECTION_HEADER },
      { id: 'ssi_site', label: 'Zakażenie miejsca operowanego', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'sepsis_30d', label: 'Posocznica', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'stentgraft_infection', label: 'Zakażenie stentgraftu', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_l_bleed', label: 'KRWAWIENIE', type: FieldType.SECTION_HEADER },
      { id: 'bleeding_barc_ge_3', label: 'Duże krwawienie (BARC >=3)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'prbc_units_transfused', label: 'Przetoczone jednostki KKCz', type: FieldType.NUMBER },
      { id: 'reop_for_bleeding', label: 'Reoperacja z powodu krwawienia', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'hdr_l_other', label: 'INNE', type: FieldType.SECTION_HEADER },
      { id: 'bowel_ischemia', label: 'Niedokrwienie jelit', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'arm_ischemia_lsa', label: 'Niedokrwienie lewej ręki (jeśli pokryto LSA)', type: FieldType.RADIO, options: YES_NO_UNKNOWN }
    ]
  },
  {
    id: 'sec_m_death',
    title: 'Sekcja M: Śmiertelność',
    description: 'Przyczyny zgonów v1.1',
    fields: [
      { id: 'death_any_30d', label: 'Zgon w ciągu 30 dni', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'death_date', label: 'Jeśli tak - data zgonu', type: FieldType.DATE },
      { id: 'death_days_from_proc_final', label: 'Dni od zabiegu do zgonu', type: FieldType.NUMBER },
      { id: 'hdr_m_classification', label: 'SZCZEGÓŁOWA KLASYFIKACJA ZGONU', type: FieldType.SECTION_HEADER },
      { id: 'death_category', label: 'Kategoria zgonu', type: FieldType.RADIO, options: [{label: 'Związany z aortą', value: 'aorta'}, {label: 'Związany z zabiegiem (nie-aortalny)', value: 'procedure'}, {label: 'Niezwiązany z zabiegiem', value: 'unrelated'}] },
      { id: 'death_cause_non_aortic', label: 'Jeśli zgon związany z zabiegiem (nie-aortalny) - przyczyna', type: FieldType.SELECT, options: [{label: 'Krwawienie z dostępu', value: 'bleeding_access'}, {label: 'Udar', value: 'stroke'}, {label: 'Zawał serca', value: 'mi'}, {label: 'Posocznica', value: 'sepsis'}, {label: 'Niewydolność oddechowa', value: 'resp'}, {label: 'Inna', value: 'other'}] },
      { id: 'hdr_m_analysis', label: 'ANALIZA: SUKCES TECHNICZNY VS ZGON', type: FieldType.SECTION_HEADER },
      { id: 'tech_success_100', label: 'Sukces techniczny 100%', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'tech_success_100_death_note', label: 'Jeśli sukces 100% a zgon - wyjaśnienie', type: FieldType.TEXTAREA },
      { id: 'hdr_m_timing', label: 'STRATYFIKACJA CZASOWA ZGONU', type: FieldType.SECTION_HEADER },
      { id: 'death_timeframe', label: 'Czas zgonu od zabiegu', type: FieldType.RADIO, options: [{label: '0-24h', value: '0_24h'}, {label: '1-3 dni', value: '1_3d'}, {label: '4-7 dni', value: '4_7d'}, {label: '8-14 dni', value: '8_14d'}, {label: '15-30 dni', value: '15_30d'}] },
      { id: 'death_comment', label: 'Komentarz', type: FieldType.TEXTAREA },
      { id: 'death_cause_main', label: 'Główna przyczyna zgonu (archiwum)', type: FieldType.SELECT, options: [{label: 'Udar niedokrwienny', value: 'str_i'}, {label: 'Udar krwotoczny', value: 'str_h'}, {label: 'Pęknięcie aorty', value: 'rupt'}, {label: 'Sercowa', value: 'card'}, {label: 'Posocznica', value: 'sepsis'}, {label: 'Niewydolność oddechowa', value: 'resp'}, {label: 'Wielonarządowa', value: 'mods'}, {label: 'Inna', value: 'other'}] },
      { id: 'death_classification_final', label: 'Klasyfikacja zgonu (archiwum)', type: FieldType.SELECT, options: [{label: 'Związany z aortą', value: 'aorta'}, {label: 'Sercowo-naczyniowy (nie-aortalny)', value: 'cv'}, {label: 'Neurologiczny', value: 'neuro'}, {label: 'Inny', value: 'other'}] },
      { id: 'autopsy_performed', label: 'Wykonano sekcję zwłok', type: FieldType.RADIO, options: YES_NO_UNKNOWN }
    ]
  },
  {
    id: 'sec_n_followup',
    title: 'Sekcja N: Obserwacja (Follow-up)',
    description: 'Wyniki długofalowe v1.1',
    fields: [
      { id: 'followup_last_visit_date', label: 'Data ostatniej wizyty kontrolnej', type: FieldType.DATE },
      { id: 'followup_time_days', label: 'Czas obserwacji (dni)', type: FieldType.NUMBER },
      { id: 'followup_status', label: 'Status w obserwacji', type: FieldType.RADIO, options: [{label: 'Żyje', value: 'alive'}, {label: 'Zmarł', value: 'dead'}, {label: 'Utracony z obserwacji', value: 'lost'}] },
      { id: 'followup_mrs', label: 'mRS przy ostatniej wizycie', type: FieldType.NUMBER, unit: '/6' },
      { id: 'late_stroke_gt_30d', label: 'Późny udar (>30 dni)', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'reintervention_required', label: 'Wymagana reinterwencja', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'control_endoleak_found', label: 'Przeciek w kontrolnym badaniu obrazowym', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'branch_patency_confirmed', label: 'Potwierdzona drożność naczyń odgałęzionych', type: FieldType.RADIO, options: YES_NO_UNKNOWN }
    ]
  },
  {
    id: 'sec_o_quality',
    title: 'Sekcja O: Jakość i Kompletność Danych',
    description: 'Weryfikacja v1.1',
    fields: [
      { id: 'mandatory_fields_filled', label: 'Wszystkie obowiązkowe pola wypełnione', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'source_docs_available', label: 'Dokumentacja źródłowa dostępna', type: FieldType.RADIO, options: YES_NO_UNKNOWN },
      { id: 'data_entry_initials', label: 'Wprowadził (inicjały)', type: FieldType.TEXT },
      { id: 'data_entry_date', label: 'Data wprowadzenia danych', type: FieldType.DATE },
      { id: 'verification_initials', label: 'Zweryfikował (inicjały)', type: FieldType.TEXT },
      { id: 'verification_date', label: 'Data weryfikacji', type: FieldType.DATE }
    ]
  }
];

const generateMockData = () => {
  const records = [];
  const startYear = 2024;
  
  // Indication and disease arrays
  const indications = ['tetniak', 'rozwarstwienie'];
  const ethnicities = ['kaukaskie', 'afrykanskie', 'azjatyckie'];
  const smokingStatus = ['nigdy', 'byly', 'aktualny'];
  const strokeAreas = ['mca', 'aca', 'pca', 'vb'];
  const stentgrafts = ['nexus', 'relay', 'cook'];
  const configs = ['branched', 'modular'];
  const aneurysmSizeCategories = ['lt50', '50_59', '60_69', '70_79', 'ge80'];
  const aneurysmLocations = ['asc', 'arch', 'desc_p', 'multi'];
  const treatedVessels = ['bct', 'lcca', 'lsa', 'multi'];
  const mainAccessSites = ['fem_s', 'fem_p', 'conduit', 'direct'];
  const addAccessSites = ['rad_r', 'rad_l', 'brach_r', 'brach_l', 'ax_r', 'ax_l'];
  
  for (let i = 1; i <= 50; i++) {
    const isFemale = Math.random() > 0.5;
    const age = 62 + Math.floor(Math.random() * 20);
    const urgency = Math.random() > 0.8 ? 'emergency' : 'elective';
    const hasShaggy = Math.random() > 0.7 ? 'tak' : 'nie';
    const hasIncompleteCow = Math.random() > 0.5;
    const hasEpd = urgency === 'elective' ? (Math.random() > 0.2 ? 'tak' : 'nie') : (Math.random() > 0.7 ? 'tak' : 'nie');
    
    let strokeProb = 0.04;
    if (hasShaggy === 'tak') strokeProb += 0.15;
    if (hasIncompleteCow) strokeProb += 0.08;
    if (hasEpd === 'nie') strokeProb += 0.10;
    if (urgency !== 'elective') strokeProb += 0.12;

    const hasStroke = Math.random() < strokeProb ? 'tak' : 'nie';
    // Always assign a stroke type to stroke patients
    const strokeTypeRand = Math.random();
    const strokeType = strokeTypeRand < 0.70 ? 'isch' : strokeTypeRand < 0.85 ? 'hem' : strokeTypeRand < 0.95 ? 'mix' : 'unk';
    const contrastVol = 90 + Math.floor(Math.random() * 140);
    const baselineCreat = 70 + Math.floor(Math.random() * 60);
    const hasAki = (contrastVol > 180 || baselineCreat > 110) && Math.random() > 0.7 ? 'tak' : 'nie';
    const isDead = (hasStroke === 'tak' && Math.random() > 0.8) || (Math.random() < 0.03) ? 'tak' : 'nie';
    
    const indication = indications[Math.floor(Math.random() * indications.length)];

    const data: Record<string, any> = {
      // Section A - Administrative
      study_number: `SA-${1000 + i}`,
      center_code: 'PL-01',
      inclusion_date: `2024-02-${String(1 + Math.floor(Math.random() * 25)).padStart(2, '0')}`,
      collector_initials: 'JK',
      
      // Section B - Demographics
      dob: `${1960 + age}-${String(1 + Math.floor(Math.random() * 12)).padStart(2, '0')}-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}`,
      age,
      sex: isFemale ? 'k' : 'm',
      height: isFemale ? 160 + Math.floor(Math.random() * 10) : 175 + Math.floor(Math.random() * 10),
      weight: isFemale ? 60 + Math.floor(Math.random() * 20) : 80 + Math.floor(Math.random() * 25),
      bmi: isFemale ? 24 + Math.random() * 4 : 26 + Math.random() * 3,
      smoking_status: smokingStatus[Math.floor(Math.random() * smokingStatus.length)],
      
      // Section C - Comorbidities
      htn: 'tak',
      cad: Math.random() > 0.6 ? 'tak' : 'nie',
      mi_history: Math.random() > 0.8 ? 'tak' : 'nie',
      heart_failure_nyha: Math.random() > 0.7 ? '0' : Math.random() > 0.5 ? '1' : '2',
      afib: Math.random() > 0.75 ? 'tak' : 'nie',
      prev_cardio_sx: Math.random() > 0.85 ? 'tak' : 'nie',
      pfo_history: Math.random() > 0.85 ? 'tak' : 'nie',
      other_shunt: Math.random() > 0.9 ? 'tak' : 'nie',
      pad: Math.random() > 0.8 ? 'tak' : 'nie',
      prior_stentgraft_yn: Math.random() > 0.9 ? 'tak' : Math.random() > 0.5 ? 'nie' : 'nieznane',
      prior_stentgraft_type: Math.random() > 0.9 ? 'tevar' : Math.random() > 0.6 ? 'bevar' : 'evar',
      prior_stentgraft_date: Math.random() > 0.9 ? `2022-${String(1 + Math.floor(Math.random() * 12)).padStart(2, '0')}-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}` : '',
      prior_cardiac_sx_type: Math.random() > 0.85 ? 'bentalla_synthetic' : Math.random() > 0.6 ? 'cabg' : 'other',
      synthetic_valve_diam: Math.random() > 0.85 ? 19 + Math.floor(Math.random() * 6) : 0,
      cardiac_sx_technique: Math.random() > 0.85 ? 'through_valve' : Math.random() > 0.5 ? 'loop' : 'nd',
      stroke_isch: Math.random() > 0.7 ? 'tak' : 'nie',
      stroke_hem: Math.random() > 0.9 ? 'tak' : 'nie',
      stroke_tia: Math.random() > 0.8 ? 'tak' : 'nie',
      carotid_stenosis_gt50: Math.random() > 0.85 ? 'tak' : 'nie',
      cea_stent_history: Math.random() > 0.9 ? 'tak' : 'nie',
      cognitive_impairment: Math.random() > 0.88 ? 'tak' : 'nie',
      stroke_count: Math.random() > 0.7 ? Math.floor(Math.random() * 3) + 1 : 0,
      last_stroke_date: Math.random() > 0.7 ? `2023-${String(1 + Math.floor(Math.random() * 12)).padStart(2, '0')}-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}` : '',
      time_from_stroke_months: Math.random() > 0.7 ? Math.floor(Math.random() * 24) : 0,
      stroke_area: Math.random() > 0.7 ? strokeAreas[Math.floor(Math.random() * strokeAreas.length)] : '',
      permanent_neuro_deficit: Math.random() > 0.7 ? 'tak' : Math.random() > 0.5 ? 'nie' : 'nieznane',
      pre_proc_mrs: Math.floor(Math.random() * 5),
      dm: Math.random() > 0.7 ? 'tak' : 'nie',
      copd: Math.random() > 0.85 ? 'tak' : 'nie',
      chronic_kidney: Math.random() > 0.8 ? 'tak' : 'nie',
      dialysis: Math.random() > 0.95 ? 'tak' : 'nie',
      connective_tissue_disease: Math.random() > 0.9 ? 'tak' : 'nie',
      active_cancer: Math.random() > 0.9 ? 'tak' : 'nie',
      baseline_egfr: Math.floor(90 - (baselineCreat / 10)),
      baseline_creat: baselineCreat,
      baseline_hb: 11 + Math.random() * 4,
      post_procedure_hb: 9 + Math.random() * 3,
      ct_type: Math.random() > 0.95 ? 'marfan' : 'inna',
      ct_dx_age: Math.random() > 0.95 ? 45 : 0,
      
      // Section D - Pathology & Indication
      primary_indication: indication,
      post_bentalla: Math.random() > 0.9 ? 'synthetic' : Math.random() > 0.6 ? 'biologic' : 'no',
      dissection_entry_zone: indication === 'rozwarstwienie' ? String(Math.floor(Math.random() * 13)) : '',
      dissection_reentry_zone: indication === 'rozwarstwienie' ? String(Math.floor(Math.random() * 13)) : '',
      rcca_status: indication === 'rozwarstwienie' ? ['compressed', 'stent', 'no_stent', 'none'][Math.floor(Math.random() * 4)] : 'none',
      lcca_status: indication === 'rozwarstwienie' ? ['compressed', 'stent', 'no_stent', 'none'][Math.floor(Math.random() * 4)] : 'none',
      lsa_status: indication === 'rozwarstwienie' ? ['compressed', 'stent', 'no_stent', 'none'][Math.floor(Math.random() * 4)] : 'none',
      bct_status: indication === 'rozwarstwienie' ? ['compressed', 'stent', 'no_stent', 'none'][Math.floor(Math.random() * 4)] : 'none',
      pau_depth: indication === 'ulcer' ? 5 + Math.floor(Math.random() * 15) : 0,
      pau_width: indication === 'ulcer' ? 3 + Math.floor(Math.random() * 10) : 0,
      pau_zone: indication === 'ulcer' ? Math.floor(Math.random() * 6) : 0,
      indication_specify: Math.random() > 0.7 ? 'pseudotetniak' : '',
      aortic_diameter_mm: 50 + Math.floor(Math.random() * 40),
      aortic_diameter_proximal: 45 + Math.floor(Math.random() * 30),
      aortic_diameter_distal: 40 + Math.floor(Math.random() * 20),
      aortic_location: Math.random() > 0.5 ? 'thoracic' : 'aaaa',
      shaggy_aorta: hasShaggy,
      thrombus_aorta: Math.random() > 0.85 ? 'tak' : 'nie',
      willis_classification: hasIncompleteCow ? 'inc_both' : 'full',
      CoW_specify: hasIncompleteCow ? 'inc_anterior' : '',
      intracranial_stenosis: Math.random() > 0.8 ? 'tak' : 'nie',
      
      // Aneurysm-specific fields (Section D - Pathology)
      aneurysm_max_diam: indication === 'tetniak' ? 55 + Math.floor(Math.random() * 50) : 0,
      aneurysm_loc: indication === 'tetniak' ? aneurysmLocations[Math.floor(Math.random() * aneurysmLocations.length)] : '',
      aneurysm_size_cat: indication === 'tetniak' ? aneurysmSizeCategories[Math.floor(Math.random() * aneurysmSizeCategories.length)] : '',
      aneurysm_gt_70: indication === 'tetniak' ? (Math.random() > 0.5 ? 'tak' : 'nie') : 'nieznane',
      aneurysm_symptomatic: indication === 'tetniak' ? (Math.random() > 0.7 ? 'tak' : 'nie') : 'nieznane',
      aneurysm_rupture_cont: indication === 'tetniak' ? (Math.random() > 0.8 ? 'tak' : 'nie') : 'nieznane',
      
      // Dissection-specific fields (Section D - Pathology)
      stanford_class: indication === 'rozwarstwienie' ? (Math.random() > 0.5 ? 'a' : 'b') : '',
      dissection_phase: indication === 'rozwarstwienie' ? ['acute', 'subacute', 'chronic'][Math.floor(Math.random() * 3)] : '',
      malperfusion_syndrome: indication === 'rozwarstwienie' ? (Math.random() > 0.7 ? 'tak' : 'nie') : 'nieznane',
      
      // Morphology fields
      arch_type_ishimaru: ['1', '2', '3'][Math.floor(Math.random() * 3)],
      thrombus_in_arch: Math.random() > 0.8 ? 'tak' : 'nie',
      thrombus_in_asc: Math.random() > 0.85 ? 'tak' : 'nie',
      porcelain_aorta: Math.random() > 0.9 ? 'tak' : 'nie',
      supraaortic_vessels_inv: ['none', 'bct', 'lcca', 'lsa', 'multi'][Math.floor(Math.random() * 5)],
      
      // Section E - Vascular Anatomy (Preoperative)
      acom_patent: Math.random() > 0.3 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      segment_a1_aca: ['both', 'r_dom', 'l_dom', 'hypo'][Math.floor(Math.random() * 4)],
      r_pcom_patent: Math.random() > 0.5 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      l_pcom_patent: Math.random() > 0.5 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      r_va_status: ['patent', 'hypo', 'pica', 'occl', 'na'][Math.floor(Math.random() * 5)],
      r_va_pathology: ['stenosis', 'thrombosis', 'dissection', 'none'][Math.floor(Math.random() * 4)],
      l_va_status: ['patent', 'hypo', 'pica', 'occl', 'na'][Math.floor(Math.random() * 5)],
      l_va_pathology: ['stenosis', 'thrombosis', 'dissection', 'none'][Math.floor(Math.random() * 4)],
      va_dominance: ['codom', 'r_dom', 'l_dom'][Math.floor(Math.random() * 3)],
      r_ica_status: ['patent', 'sten_lt50', 'sten_50_69', 'sten_70_99', 'occl'][Math.floor(Math.random() * 5)],
      l_ica_status: ['patent', 'sten_lt50', 'sten_50_69', 'sten_70_99', 'occl'][Math.floor(Math.random() * 5)],
      posterior_risk: ['low', 'med', 'high'][Math.floor(Math.random() * 3)],
      
      // Section F - Cardiac Evaluation
      cardio_consult_done: Math.random() > 0.3 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      cardio_consult_date: `2024-01-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}`,
      echo_type: Math.random() > 0.5 ? 'tte' : Math.random() > 0.5 ? 'tee' : 'both',
      lvef_perc: 45 + Math.floor(Math.random() * 35),
      lv_function: Math.random() > 0.5 ? 'norm' : 'mild',
      aortic_insuf_grade: Math.random() > 0.7 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      aortic_sten_grade: ['none', 'mild', 'mod'][Math.floor(Math.random() * 3)],
      pfo_detected: Math.random() > 0.8 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      asd_detected: Math.random() > 0.95 ? 'tak' : 'nie',
      laa_thrombus: Math.random() > 0.98 ? 'tak' : 'nie',
      coronary_eval_method: ['ct', 'angio', 'stress', 'none'][Math.floor(Math.random() * 4)],
      cad_status: ['none', 'non_obt', '1v', '2v', '3v'][Math.floor(Math.random() * 5)],
      revasc_required_pre_aorta: Math.random() > 0.9 ? 'tak' : 'nie',
      
      // Section E - Procedure Details
      urgency_proc: urgency,
      proc_date: `2024-01-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}`,
      proc_location: Math.random() > 0.5 ? 'hybrid' : 'conv',
      operator_1_init: 'JK',
      operator_2_init: Math.random() > 0.5 ? 'MS' : 'AP',
      main_access: ['fem_r', 'fem_l', 'conduit', 'aortal'][Math.floor(Math.random() * 4)],
      main_sheath_fr: 22 + Math.floor(Math.random() * 6),
      add_access_site: ['temporal_r', 'temporal_l', 'subclavian_r', 'carotid_l', 'rad_r', 'rad_l', 'brach_r', 'brach_l', 'ax_r', 'ax_l'][Math.floor(Math.random() * 10)],
      stentgraft_system: stentgrafts[Math.floor(Math.random() * stentgrafts.length)],
      stentgraft_size: '40-28-32/221',
      nexus_config: Math.random() > 0.5 ? 'lifs_lcca_lsa' : 'lifs_lcca',
      cook_config: ['3ab', '2ab', 'cmd_lcca_lsa', '3ab_retro_lcca_lsa', '3ab_retro_bct_lcca_lsa'][Math.floor(Math.random() * 5)],
      cook_lsa_strategy: ['retro', 'ante', 'fen', 'not_treated'][Math.floor(Math.random() * 4)],
      cook_lcca_strategy: ['retro', 'ante', 'fen', 'scallop', 'not_treated'][Math.floor(Math.random() * 5)],
      cook_bct_strategy: ['retro', 'ante', 'scallop', 'not_treated'][Math.floor(Math.random() * 4)],
      bct_order: Math.random() > 0.7 ? 1 : Math.random() > 0.5 ? 2 : 3,
      lcca_order: Math.random() > 0.7 ? 1 : Math.random() > 0.5 ? 2 : 3,
      lsa_order: Math.random() > 0.7 ? 1 : Math.random() > 0.5 ? 2 : 3,
      
      // BCT Stents (Section G Part 2)
      bct_stent1_type: ['cmd', 'vbx', 'bgp', 'zilver'][Math.floor(Math.random() * 4)],
      bct_stent1_diam: 6 + Math.random() * 2,
      bct_stent1_len: 20 + Math.floor(Math.random() * 20),
      bct_stent2_type: Math.random() > 0.6 ? ['cmd', 'vbx', 'bgp', 'zilver'][Math.floor(Math.random() * 4)] : '',
      bct_stent2_diam: Math.random() > 0.6 ? 6 + Math.random() * 2 : 0,
      bct_stent2_len: Math.random() > 0.6 ? 20 + Math.floor(Math.random() * 20) : 0,
      bct_stent3_type: Math.random() > 0.85 ? ['vbx', 'bgp', 'zilver'][Math.floor(Math.random() * 3)] : '',
      bct_stent3_diam: Math.random() > 0.85 ? 6 + Math.random() * 2 : 0,
      bct_stent3_len: Math.random() > 0.85 ? 20 + Math.floor(Math.random() * 20) : 0,
      
      // LCCA Stents (Section G Part 2)
      lcca_stent1_type: ['vbx', 'bgp', 'zilver'][Math.floor(Math.random() * 3)],
      lcca_stent1_diam: 6 + Math.random() * 2,
      lcca_stent1_len: 20 + Math.floor(Math.random() * 20),
      lcca_stent2_type: Math.random() > 0.6 ? ['vbx', 'bgp', 'zilver', 'nd'][Math.floor(Math.random() * 4)] : '',
      lcca_stent2_diam: Math.random() > 0.6 ? 6 + Math.random() * 2 : 0,
      lcca_stent2_len: Math.random() > 0.6 ? 20 + Math.floor(Math.random() * 20) : 0,
      lcca_stent3_type: Math.random() > 0.85 ? ['vbx', 'bgp', 'zilver', 'nd'][Math.floor(Math.random() * 4)] : '',
      lcca_stent3_diam: Math.random() > 0.85 ? 6 + Math.random() * 2 : 0,
      lcca_stent3_len: Math.random() > 0.85 ? 20 + Math.floor(Math.random() * 20) : 0,
      
      // LSA Stents (Section G Part 2)
      lsa_stent1_type: ['vbx', 'bgp', 'zilver'][Math.floor(Math.random() * 3)],
      lsa_stent1_diam: 6 + Math.random() * 2,
      lsa_stent1_len: 20 + Math.floor(Math.random() * 20),
      lsa_stent2_type: Math.random() > 0.6 ? ['vbx', 'bgp', 'zilver', 'nd'][Math.floor(Math.random() * 4)] : '',
      lsa_stent2_diam: Math.random() > 0.6 ? 6 + Math.random() * 2 : 0,
      lsa_stent2_len: Math.random() > 0.6 ? 20 + Math.floor(Math.random() * 20) : 0,
      lsa_stent3_type: Math.random() > 0.85 ? ['vbx', 'bgp', 'zilver', 'nd'][Math.floor(Math.random() * 4)] : '',
      lsa_stent3_diam: Math.random() > 0.85 ? 6 + Math.random() * 2 : 0,
      lsa_stent3_len: Math.random() > 0.85 ? 20 + Math.floor(Math.random() * 20) : 0,
      
      // Total Stents
      total_stents_implanted: 3 + Math.floor(Math.random() * 6),
      
      access_artery: Math.random() > 0.5 ? 'femoral' : 'axillary',
      anesthesia_type: Math.random() > 0.7 ? 'local' : 'general',
      stent_diameter: 28 + Math.floor(Math.random() * 8),
      proc_config: configs[Math.floor(Math.random() * configs.length)],
      nirs_used: 'tak',
      epd_used_proc: hasEpd,
      
      // Section I - Embolic Protection
      continuous_flush_used: 'tak',
      flush_fluid_type: 'std',
      flush_pressure_target: Math.random() > 0.2 ? 'tak' : 'nie',
      flush_rate_drops_per_sec: 1 + Math.random() * 1.5,
      sg_flush_technique: ['co2_sal', 'retro', 'other'][Math.floor(Math.random() * 3)],
      sg_air_removed_confirmed: Math.random() > 0.1 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      epd_indication: hasEpd === 'tak' ? ['shaggy', 'thromb_arch', 'routine', 'other'][Math.floor(Math.random() * 4)] : '',
      epd_device: hasEpd === 'tak' ? ['spider', 'sentinel', 'triguard'][Math.floor(Math.random() * 3)] : '',
      epd_protected_vessels: hasEpd === 'tak' ? ['r_cca', 'lcca', 'both'][Math.floor(Math.random() * 3)] : '',
      epd_access_site: hasEpd === 'tak' ? ['rad_r', 'rad_l', 'brach', 'fem'][Math.floor(Math.random() * 4)] : '',
      epd_sheath_fr: hasEpd === 'tak' ? 6 + Math.floor(Math.random() * 3) : 0,
      epd_removed_success: hasEpd === 'tak' ? (Math.random() > 0.05 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')) : '',
      epd_material_visible: hasEpd === 'tak' ? (Math.random() > 0.7 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')) : '',
      epd_material_desc: hasEpd === 'tak' && Math.random() > 0.7 ? 'Drobne fibryno-plateletowe złogi' : '',
      epd_to_pathology: hasEpd === 'tak' ? (Math.random() > 0.5 ? 'tak' : 'nie') : '',
      
      // Section J - Awakening and Completion
      verbal_contact_or: Math.random() > 0.85 ? 'yes' : 'no',
      motor_deficit_or: Math.random() > 0.9 ? 'none' : ['kg', 'kd', 'both'][Math.floor(Math.random() * 3)],
      neuro_notes_or: Math.random() > 0.8 ? 'Pacjent przytomny, w dobrym kontakcie, bez deficytów' : '',
      awakening_time_icu: `${8 + Math.floor(Math.random() * 16)}:${String(Math.floor(Math.random() * 60)).padStart(2, '0')}`,
      time_to_awakening_hours: 2 + Math.floor(Math.random() * 6),
      verbal_contact_icu: Math.random() > 0.9 ? 'yes' : (Math.random() > 0.5 ? 'no' : 'yes'),
      motor_deficit_icu: Math.random() > 0.92 ? 'none' : ['kg', 'kd'][Math.floor(Math.random() * 2)],
      gcs_icu: 12 + Math.floor(Math.random() * 3),
      neuro_notes_icu: 'Pacjent wybudzony, przytomny, bez nowych deficytów neurologicznych',
      intraop_angio_neuro_done: Math.random() > 0.7 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      intraop_angio_neuro_result: Math.random() > 0.7 ? 'patent' : 'occl',
      tech_success: Math.random() > 0.15 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      
      proc_time_total_min: 140 + Math.floor(Math.random() * 80),
      setup_time_min: 20 + Math.floor(Math.random() * 15),
      fluoro_time_min: 30 + Math.floor(Math.random() * 45),
      contrast_vol_ml: contrastVol,
      blood_loss_ml: 50 + Math.floor(Math.random() * 300),
      fluid_administered_ml: 1000 + Math.floor(Math.random() * 2000),
      transfusion_needed: Math.random() > 0.95 ? 'tak' : 'nie',
      transfusion_type: 'prbc',
      units_transfused: Math.floor(Math.random() * 4),
      procedural_complications: Math.random() > 0.9 ? 'tak' : 'nie',
      complication_type: Math.random() > 0.95 ? 'dissection' : '',
      complication_managed: 'interventional',
      endoleak_type_1: Math.random() > 0.85 ? 'tak' : 'nie',
      endoleak_type_2: Math.random() > 0.95 ? 'tak' : 'nie',
      endoleak_type_3: Math.random() > 0.98 ? 'tak' : 'nie',
      branch_vessel_occlusion: Math.random() > 0.9 ? 'nie' : (Math.random() > 0.5 ? 'tak' : 'nieznane'),
      open_conversion: Math.random() > 0.98 ? 'tak' : 'nie',
      unplanned_addon_proc: Math.random() > 0.92 ? 'tak' : 'nie',
      tech_limit_encountered: Math.random() > 0.8 ? 'nie' : (Math.random() > 0.5 ? 'tak' : 'nieznane'),
      tech_limit_type: Math.random() > 0.8 ? '' : ['size', 'angle', 'length', 'other'][Math.floor(Math.random() * 4)],
      tech_limit_desc: Math.random() > 0.85 ? '' : 'Kąt odejścia LCCA utrudniał kanulację - rozwiązano retrograde access',
      
      sci_any: Math.random() > 0.92 ? 'tak' : 'nie',
      sci_severity: Math.random() > 0.92 ? (Math.random() > 0.5 ? 'weak' : 'paral') : '',
      sci_onset_h_post_proc: Math.random() > 0.92 ? 2 + Math.floor(Math.random() * 12) : 0,
      
      // Section G - Procedural (Device & Access)
      treated_arch_branches_count: ['1', '2', '3'][Math.floor(Math.random() * 3)],
      treated_vessels: treatedVessels[Math.floor(Math.random() * treatedVessels.length)],
      lsa_coverage_no_revasc: Math.random() > 0.8 ? 'tak' : 'nie',
      bypass_cs_p: Math.random() > 0.85 ? 'tak' : 'nie',
      
      // Section G - Treatment Staging
      treatment_type: ['ab_only', 'ab_plus', 'fmj'][Math.floor(Math.random() * 3)],
      pre_ab_stentgraft_yn: Math.random() > 0.7 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      pre_ab_procedure_date: Math.random() > 0.7 ? `2023-${String(1 + Math.floor(Math.random() * 12)).padStart(2, '0')}-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}` : '',
      pre_ab_procedure_type: Math.random() > 0.7 ? ['tevar', 'bevar', 'fevar', 'evar', 'ibd'][Math.floor(Math.random() * 5)] : '',
      pre_ab_procedure_notes: Math.random() > 0.8 ? 'Wcześniejszy TEVAR - doskonała pozycja dla AB' : '',
      during_ab_stentgraft_yn: Math.random() > 0.8 ? 'tak' : (Math.random() > 0.6 ? 'nie' : 'nieznane'),
      during_ab_procedure_type: Math.random() > 0.8 ? ['bevar', 'evar', 'ibd'][Math.floor(Math.random() * 3)] : '',
      during_ab_procedure_notes: Math.random() > 0.85 ? 'Połączony BEVAR w tym samym zabiegu' : '',
      post_ab_planned_yn: Math.random() > 0.6 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      post_ab_procedure_date: Math.random() > 0.6 ? `2024-${String(1 + Math.floor(Math.random() * 12)).padStart(2, '0')}-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}` : '',
      post_ab_procedure_type: Math.random() > 0.6 ? ['bevar', 'evar', 'tevar', 'ibd'][Math.floor(Math.random() * 4)] : '',
      post_ab_procedure_status: Math.random() > 0.6 ? (Math.random() > 0.5 ? 'planned' : 'executed') : (Math.random() > 0.5 ? 'cancelled' : 'nd'),
      post_ab_procedure_notes: Math.random() > 0.7 ? 'Planowany BEVAR w Follow-upie' : '',
      
      // Section H - Intraoperative Hemodynamics
      rso2_baseline_r: 60 + Math.floor(Math.random() * 20),
      rso2_baseline_l: 60 + Math.floor(Math.random() * 20),
      rso2_lowest_r: 45 + Math.floor(Math.random() * 15),
      rso2_lowest_l: 45 + Math.floor(Math.random() * 15),
      rso2_alert_triggered: Math.random() > 0.7 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      rso2_pre_stim_r: 62 + Math.floor(Math.random() * 18),
      rso2_pre_stim_l: 62 + Math.floor(Math.random() * 18),
      rso2_during_stim_r: 35 + Math.floor(Math.random() * 20),
      rso2_during_stim_l: 35 + Math.floor(Math.random() * 20),
      map_baseline: 85 + Math.floor(Math.random() * 15),
      map_highest: 110 + Math.floor(Math.random() * 20),
      map_lowest: 65 + Math.floor(Math.random() * 15),
      map_at_deployment: 75 + Math.floor(Math.random() * 20),
      hr_reduction_method: ['none', 'rvp', 'valsalva', 'ivc_balloon'][Math.floor(Math.random() * 4)],
      map_pre_stentgraft: Math.random() > 0.6 ? 82 + Math.floor(Math.random() * 18) : 0,
      map_post_stentgraft: 78 + Math.floor(Math.random() * 22),
      pacing_abandoned_reason: Math.random() > 0.75 ? 'MAP stabilne, brak wskazań do stymulacji' : '',
      heparin_dose_total: 5000 + Math.floor(Math.random() * 3000),
      baseline_act: 110 + Math.floor(Math.random() * 40),
      peak_act: 270 + Math.floor(Math.random() * 50),
      act_target_maintained: Math.random() > 0.3 ? 'tak' : 'nie',
      protamine_given: Math.random() > 0.6 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      protamine_dose: Math.random() > 0.6 ? 50 + Math.floor(Math.random() * 100) : 0,
      rapid_pacing_used: Math.random() > 0.4 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      pacing_episodes_count: Math.random() > 0.4 ? 1 + Math.floor(Math.random() * 4) : 0,
      pacing_time_total: Math.random() > 0.4 ? 15 + Math.floor(Math.random() * 45) : 0,
      
      // Section K - Neurological Outcomes
      new_neuro_deficit_at_wake: hasStroke === 'tak' ? 'tak' : (Math.random() > 0.95 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')),
      time_to_first_neuro_eval_h: 0.5 + Math.random() * 4,
      gcs_at_wake: hasStroke === 'tak' ? 10 + Math.floor(Math.random() * 5) : 15,
      motor_deficit: hasStroke === 'tak' ? 'tak' : (Math.random() > 0.9 ? 'tak' : 'nie'),
      speech_deficit: hasStroke === 'tak' ? (Math.random() > 0.5 ? 'tak' : 'nie') : 'nie',
      vision_deficit: Math.random() > 0.95 ? 'tak' : 'nie',
      stroke_date: hasStroke === 'tak' ? `2024-01-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}` : '',
      stroke_time_from_proc_h: hasStroke === 'tak' ? Math.floor(Math.random() * 24) : 0,
      stroke_area_cat: hasStroke === 'tak' ? ['mca', 'aca', 'pca', 'vb', 'ws', 'multi'][Math.floor(Math.random() * 6)] : '',
      stroke_side: hasStroke === 'tak' ? ['r', 'l', 'bilat'][Math.floor(Math.random() * 3)] : '',
      stroke_imaging_confirmed: hasStroke === 'tak' ? (Math.random() > 0.1 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')) : '',
      stroke_classification_30d: hasStroke === 'tak' ? (Math.random() > 0.5 ? 'small' : 'large') : '',
      corr_asc_aorta_ge_40: hasStroke === 'tak' ? (Math.random() > 0.5 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')) : 'nie',
      corr_prev_stroke_tia: hasStroke === 'tak' ? (Math.random() > 0.6 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')) : 'nie',
      corr_shaggy_aorta: hasStroke === 'tak' ? (Math.random() > 0.7 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')) : 'nie',
      corr_willis_inc: hasStroke === 'tak' ? (Math.random() > 0.5 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')) : 'nie',
      corr_aneurysm_ge_70: hasStroke === 'tak' ? (Math.random() > 0.8 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')) : 'nie',
      tia_any: Math.random() > 0.95 ? 'tak' : (Math.random() > 0.8 ? 'nie' : 'nieznane'),
      tia_date: Math.random() > 0.95 ? `2024-01-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}` : '',
      tia_duration_h: Math.random() > 0.95 ? Math.floor(Math.random() * 24) : 0,
      tia_symptoms: Math.random() > 0.95 ? ['weak', 'speech', 'vision', 'dizz'][Math.floor(Math.random() * 4)] : '',
      thrombectomy_done: hasStroke === 'tak' ? (Math.random() > 0.7 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')) : 'nie',
      thrombectomy_time_to_puncture: hasStroke === 'tak' && Math.random() > 0.7 ? 180 + Math.floor(Math.random() * 300) : 0,
      thrombectomy_recanalization: hasStroke === 'tak' && Math.random() > 0.7 ? (Math.random() > 0.3 ? 'tak' : 'nie') : '',
      
      // Section F - 30-Day Outcomes (Legacy)
      any_stroke_30d: hasStroke,
      stroke_type_cat: hasStroke === 'tak' ? strokeType : '',
      stroke_subtype: hasStroke === 'tak' ? (strokeType === 'isch' ? 'territorial' : 'lobar') : '',
      stroke_hemispheric_location: Math.random() > 0.5 ? 'left' : 'right',
      nihss_at_diagnosis: hasStroke === 'tak' ? 6 + Math.floor(Math.random() * 12) : 0,
      nihss_at_24h: hasStroke === 'tak' ? 4 + Math.floor(Math.random() * 10) : 0,
      nihss_at_30d: hasStroke === 'tak' ? 2 + Math.floor(Math.random() * 8) : 0,
      mrs_at_24h: hasStroke === 'tak' ? 2 + Math.floor(Math.random() * 3) : 0,
      mrs_at_30d: hasStroke === 'tak' ? 2 + Math.floor(Math.random() * 2) : 0,
      aki_akin_ge_2: hasAki,
      max_creatinine_postproc: baselineCreat + (hasAki === 'tak' ? 20 + Math.random() * 40 : Math.random() * 10),
      
      // Section L - Complications (30-day)
      mi_30d: Math.random() > 0.98 ? 'tak' : 'nie',
      afib_new_onset: Math.random() > 0.9 ? 'tak' : 'nie',
      cardiac_arrest: Math.random() > 0.99 ? 'tak' : 'nie',
      aortic_rupture_post: Math.random() > 0.99 ? 'tak' : 'nie',
      retrograde_type_a: Math.random() > 0.98 ? 'tak' : 'nie',
      access_hematoma: Math.random() > 0.8 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      access_hematoma_intervention: Math.random() > 0.92 ? 'tak' : 'nie',
      retroperitoneal_hematoma: Math.random() > 0.95 ? 'tak' : 'nie',
      limb_ischemia_major: Math.random() > 0.93 ? 'tak' : 'nie',
      pseudoaneurysm: Math.random() > 0.95 ? 'tak' : 'nie',
      av_fistula: Math.random() > 0.95 ? 'tak' : 'nie',
      av_fistula_temporal: Math.random() > 0.97 ? 'tak' : 'nie',
      new_dialysis_required: hasAki === 'tak' ? (Math.random() > 0.7 ? 'tak' : 'nie') : 'nie',
      pneumonia_30d: Math.random() > 0.92 ? 'tak' : 'nie',
      vent_gt_48h: Math.random() > 0.88 ? 'tak' : 'nie',
      tracheostomy_required: Math.random() > 0.96 ? 'tak' : 'nie',
      ssi_site: Math.random() > 0.95 ? 'tak' : 'nie',
      sepsis_30d: Math.random() > 0.97 ? 'tak' : 'nie',
      stentgraft_infection: Math.random() > 0.98 ? 'tak' : 'nie',
      bleeding_barc_ge_3: Math.random() > 0.9 ? 'tak' : 'nie',
      prbc_units_transfused: Math.floor(Math.random() * 4),
      reop_for_bleeding: Math.random() > 0.96 ? 'tak' : 'nie',
      bowel_ischemia: Math.random() > 0.97 ? 'tak' : 'nie',
      arm_ischemia_lsa: Math.random() > 0.95 ? 'tak' : 'nie',
      access_complication: Math.random() > 0.92 ? 'tak' : 'nie',
      access_complication_type: Math.random() > 0.98 ? 'pseudoaneurysm' : '',
      
      // Section M - Mortality
      death_any_30d: isDead,
      death_date: isDead === 'tak' ? `2024-01-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}` : '',
      death_days_from_proc_final: isDead === 'tak' ? 3 + Math.floor(Math.random() * 15) : 30,
      death_category: isDead === 'tak' ? ['aorta', 'procedure', 'unrelated'][Math.floor(Math.random() * 3)] : '',
      death_cause_non_aortic: isDead === 'tak' ? (Math.random() > 0.5 ? ['bleeding_access', 'stroke', 'mi', 'sepsis', 'resp'][Math.floor(Math.random() * 5)] : '') : '',
      tech_success_100: isDead === 'tak' ? (Math.random() > 0.8 ? 'nie' : (Math.random() > 0.5 ? 'tak' : 'nieznane')) : 'tak',
      tech_success_100_death_note: isDead === 'tak' && Math.random() > 0.8 ? 'Sukces techniczny jednak zgon z powodu powikłania systemowego' : '',
      death_timeframe: isDead === 'tak' ? ['0_24h', '1_3d', '4_7d', '8_14d', '15_30d'][Math.floor(Math.random() * 5)] : '',
      death_comment: isDead === 'tak' ? 'Pacjent zmarł z powodu powikłania procedury' : '',
      death_cause_main: isDead === 'tak' ? ['str_i', 'str_h', 'rupt', 'card', 'sepsis', 'resp', 'mods'][Math.floor(Math.random() * 7)] : '',
      death_classification_final: isDead === 'tak' ? ['aorta', 'cv', 'neuro', 'other'][Math.floor(Math.random() * 4)] : '',
      autopsy_performed: isDead === 'tak' ? (Math.random() > 0.8 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')) : '',
      death_attributed_to: isDead === 'tak' ? Math.random() > 0.5 ? 'stroke' : 'other' : '',
      
      // Section N - Follow-up
      followup_last_visit_date: `2024-${String(3 + Math.floor(Math.random() * 10)).padStart(2, '0')}-${String(1 + Math.floor(Math.random() * 28)).padStart(2, '0')}`,
      followup_time_days: 60 + Math.floor(Math.random() * 270),
      followup_status: isDead === 'tak' ? 'dead' : (Math.random() > 0.95 ? 'lost' : 'alive'),
      followup_mrs: isDead === 'tak' ? 6 : (hasStroke === 'tak' ? 2 + Math.floor(Math.random() * 4) : Math.floor(Math.random() * 2)),
      late_stroke_gt_30d: Math.random() > 0.92 ? 'tak' : (Math.random() > 0.8 ? 'nie' : 'nieznane'),
      reintervention_required: Math.random() > 0.88 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      control_endoleak_found: Math.random() > 0.85 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane'),
      branch_patency_confirmed: Math.random() > 0.2 ? 'tak' : (Math.random() > 0.5 ? 'nie' : 'nieznane')
    };

    records.push({ id: crypto.randomUUID(), timestamp: new Date().toISOString(), data });
  }
  return records;
};

export const MOCK_DATA = generateMockData();
